FROM node:22.22.0-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN VITE_MOCK_MODE=true npm run build

FROM nginxinc/nginx-unprivileged:1.30.4-alpine@sha256:45ce1e2e699234253d1def7baa96218a5d00b498d1ba0cbb1a17b6bdf73d1351
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx-demo.conf /etc/nginx/conf.d/default.conf

USER 101:101
EXPOSE 3000

ENTRYPOINT ["nginx", "-g", "daemon off;"]
