import type {
  AuditLog,
  ContainerState,
  ContainerType,
  InformationContainer,
  NamingRuleResponse,
  Project,
  SecurityLevel,
} from "@/types";

export interface DesignUser {
  id: string;
  name: string;
  initials: string;
  role: string;
  org: string;
  color: string;
}

export interface DemoContainer {
  id: string;
  projectId: string;
  identifier: string;
  title: string;
  type: ContainerType;
  state: ContainerState;
  revision: string;
  security: SecurityLevel;
  naming: "pass" | "warn" | "fail";
  owner: string;
  org: string;
  updated: string;
  size: string;
  ext: string;
  discipline: string;
  issue?: string;
}

// ---------------------------------------------------------------------------
// Users (10 total)
// ---------------------------------------------------------------------------

export const designUsers: DesignUser[] = [
  {
    id: "u1",
    name: "佐藤 健一",
    initials: "佐",
    role: "BIMマネージャー",
    org: "大成設計",
    color: "#2c63e6",
  },
  {
    id: "u2",
    name: "鈴木 由美",
    initials: "鈴",
    role: "情報管理者",
    org: "大成設計",
    color: "#14a85f",
  },
  {
    id: "u3",
    name: "高橋 誠",
    initials: "高",
    role: "意匠設計",
    org: "大成設計",
    color: "#d99a26",
  },
  {
    id: "u4",
    name: "田中 浩二",
    initials: "田",
    role: "構造設計",
    org: "東和構造",
    color: "#9b59b6",
  },
  {
    id: "u5",
    name: "伊藤 さくら",
    initials: "伊",
    role: "設備設計",
    org: "日本設備工業",
    color: "#e0483b",
  },
  {
    id: "u6",
    name: "山本 大輔",
    initials: "山",
    role: "承認者 / 主任",
    org: "発注者PMO",
    color: "#0d9488",
  },
  {
    id: "u7",
    name: "中村 隆",
    initials: "中",
    role: "土木技術者",
    org: "三和エンジニアリング",
    color: "#f97316",
  },
  {
    id: "u8",
    name: "小林 美咲",
    initials: "小",
    role: "施工管理",
    org: "関西総合設計",
    color: "#ec4899",
  },
  {
    id: "u9",
    name: "渡辺 剛",
    initials: "渡",
    role: "BIM担当",
    org: "東北建設設計",
    color: "#6366f1",
  },
  {
    id: "u10",
    name: "松本 幸子",
    initials: "松",
    role: "品質管理",
    org: "南洋建設設計",
    color: "#84cc16",
  },
];

export const userById = Object.fromEntries(designUsers.map((u) => [u.id, u]));

// ---------------------------------------------------------------------------
// Projects (5 total)
// ---------------------------------------------------------------------------

export const demoProject: Project = {
  id: "demo",
  organization_id: "org-tko",
  name: "東京中央ターミナル再開発",
  code: "TKO",
  description:
    "地上48階・地下4階の複合ターミナル。鉄道・商業・オフィス・ホテルを統合。",
  status: "active",
  start_date: "2025-04-01",
  end_date: "2028-03-31",
  applied_standard: "ISO 19650-2:2018",
};

const projectOkn: Project = {
  id: "proj-okn",
  organization_id: "org-okn",
  name: "沖縄国際観光リゾート整備",
  code: "OKN",
  description:
    "沖縄本島南部の大規模国際観光リゾート開発。ホテル・コンベンション・マリーナを含む複合施設。",
  status: "active",
  start_date: "2025-07-01",
  end_date: "2027-12-31",
  applied_standard: "ISO 19650-2:2018",
};

const projectNgy: Project = {
  id: "proj-ngy",
  organization_id: "org-ngy",
  name: "名古屋都市高速道路改修工事",
  code: "NGY",
  description:
    "名古屋都市高速道路の老朽化橋梁・トンネル区間の全面改修。交通影響最小化が最重要課題。",
  status: "active",
  start_date: "2025-01-15",
  end_date: "2028-09-30",
  applied_standard: "ISO 19650-2:2018",
};

const projectOsk: Project = {
  id: "proj-osk",
  organization_id: "org-osk",
  name: "大阪港湾複合施設整備",
  code: "OSK",
  description:
    "大阪港南港地区における物流・商業・公園の複合施設整備。地盤改良・護岸改修を含む。",
  status: "suspended",
  start_date: "2024-10-01",
  end_date: "2027-03-31",
  applied_standard: "ISO 19650-3:2020",
};

const projectSkd: Project = {
  id: "proj-skd",
  organization_id: "org-skd",
  name: "仙台駅東口再開発計画",
  code: "SKD",
  description:
    "仙台駅東口周辺の再開発事業。複合商業ビル・広場整備・歩行者デッキを整備。",
  status: "completed",
  start_date: "2023-04-01",
  end_date: "2026-03-31",
  applied_standard: "ISO 19650-2:2018",
};

const projectHkr: Project = {
  id: "proj-hkr",
  organization_id: "org-hkr",
  name: "北陸新幹線延伸工事 (金沢-新大阪)",
  code: "HKR",
  description:
    "北陸新幹線の金沢以西延伸区間。山岳トンネル・高架橋・市街地地下区間を含む大規模鉄道インフラ整備。",
  status: "active",
  start_date: "2024-10-01",
  end_date: "2031-03-31",
  applied_standard: "ISO 19650-2:2018",
};

const projectSwg: Project = {
  id: "proj-swg",
  organization_id: "org-swg",
  name: "首都高速湾岸線 老朽化対策工事",
  code: "SWG",
  description:
    "東京湾岸線の老朽化橋梁・高架部の大規模補修・耐震補強工事。夜間通行規制下での施工が中心。",
  status: "active",
  start_date: "2025-04-01",
  end_date: "2029-03-31",
  applied_standard: "ISO 19650-2:2018",
};

const projectKsh: Project = {
  id: "proj-ksh",
  organization_id: "org-ksh",
  name: "九州縦貫道路 未整備区間整備",
  code: "KSH",
  description:
    "九州縦貫自動車道の未整備区間における4車線道路整備。切土・盛土・橋梁・トンネルを含む山岳区間。",
  status: "active",
  start_date: "2025-06-01",
  end_date: "2030-09-30",
  applied_standard: "ISO 19650-2:2018",
};

const projectHnd: Project = {
  id: "proj-hnd",
  organization_id: "org-hnd",
  name: "羽田空港 第4旅客ターミナル整備",
  code: "HND",
  description:
    "羽田空港の容量拡大を目的とした第4旅客ターミナルビル新設。年間5000万人規模の国際線・国内線共用施設。",
  status: "active",
  start_date: "2025-09-01",
  end_date: "2030-03-31",
  applied_standard: "ISO 19650-2:2018",
};

const projectTwg: Project = {
  id: "proj-twg",
  organization_id: "org-twg",
  name: "東京湾岸防潮堤 耐震・耐水強化事業",
  code: "TWG",
  description:
    "東京湾岸部の防潮堤・護岸の耐震補強と高潮対策。気候変動対応として堤防嵩上げを含む。",
  status: "active",
  start_date: "2025-03-01",
  end_date: "2028-12-31",
  applied_standard: "ISO 19650-3:2020",
};

export const demoProjects: Project[] = [
  demoProject,
  projectOkn,
  projectNgy,
  projectOsk,
  projectSkd,
  projectHkr,
  projectSwg,
  projectKsh,
  projectHnd,
  projectTwg,
];

// ---------------------------------------------------------------------------
// Containers — TKO (8 original)
// ---------------------------------------------------------------------------

export const demoContainers: DemoContainer[] = [
  {
    id: "c1",
    projectId: "demo",
    identifier: "TKO-ARC-XX-07-DR-A-0421",
    title: "基準階平面詳細図 (7F オフィス)",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u3",
    org: "大成設計",
    updated: "2026-05-28T11:24:00",
    size: "4.2 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c2",
    projectId: "demo",
    identifier: "TKO-STR-XX-ZZ-M3-S-0008",
    title: "全体構造解析モデル v8",
    type: "model",
    state: "Shared",
    revision: "P04.02",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-29T16:48:00",
    size: "218 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c3",
    projectId: "demo",
    identifier: "TKO-MEP-B2-B2-DR-M-0117",
    title: "地下2階 機械設備配管図",
    type: "drawing",
    state: "WIP",
    revision: "P02.05",
    security: "limited",
    naming: "warn",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-05-30T09:12:00",
    size: "7.8 MB",
    ext: "PDF",
    discipline: "設備",
    issue: "レベルコードがマスタ未登録 (B2)",
  },
  {
    id: "c4",
    projectId: "demo",
    identifier: "tko-arc-xx-12-dr-a-09",
    title: "12F 平面図 ドラフト",
    type: "drawing",
    state: "WIP",
    revision: "P01.01",
    security: "limited",
    naming: "fail",
    owner: "u3",
    org: "大成設計",
    updated: "2026-05-30T18:03:00",
    size: "3.1 MB",
    ext: "DWG",
    discipline: "意匠",
    issue: "小文字使用・連番桁数不足 (4桁必須)",
  },
  {
    id: "c5",
    projectId: "demo",
    identifier: "TKO-ARC-XX-ZZ-IFC-A-0003",
    title: "意匠統合 IFC モデル (連携用)",
    type: "ifc",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u1",
    org: "大成設計",
    updated: "2026-05-25T14:30:00",
    size: "512 MB",
    ext: "IFC",
    discipline: "意匠",
  },
  {
    id: "c6",
    projectId: "demo",
    identifier: "TKO-STR-XX-03-BCF-S-0044",
    title: "3F 梁貫通スリーブ干渉 指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.03",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-29T10:05:00",
    size: "82 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c7",
    projectId: "demo",
    identifier: "TKO-ARC-XX-XX-SP-A-0012",
    title: "内装仕上げ仕様書",
    type: "document",
    state: "Published",
    revision: "C03",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2026-05-20T13:18:00",
    size: "1.1 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c8",
    projectId: "demo",
    identifier: "TKO-MEP-XX-ZZ-M3-M-0021",
    title: "機械設備 統合モデル",
    type: "model",
    state: "WIP",
    revision: "P03.01",
    security: "confidential",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-05-30T15:42:00",
    size: "176 MB",
    ext: "RVT",
    discipline: "設備",
  },

  // OKN — 沖縄国際観光リゾート整備 (10 containers)
  {
    id: "c9",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZN1-ZZ-DR-A-0001",
    title: "ゾーン1 ホテル棟 配置計画図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u10",
    org: "南洋建設設計",
    updated: "2026-03-12T10:00:00",
    size: "5.4 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c10",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZN1-01-DR-A-0042",
    title: "ホテル棟 1F ロビー平面詳細図",
    type: "drawing",
    state: "Shared",
    revision: "P03.01",
    security: "limited",
    naming: "pass",
    owner: "u10",
    org: "南洋建設設計",
    updated: "2026-04-18T14:30:00",
    size: "6.2 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c11",
    projectId: "proj-okn",
    identifier: "OKN-STR-ZN1-ZZ-M3-S-0005",
    title: "ホテル棟 構造統合モデル",
    type: "model",
    state: "WIP",
    revision: "P02.03",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-10T09:15:00",
    size: "245 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c12",
    projectId: "proj-okn",
    identifier: "OKN-MEP-ZN2-ZZ-DR-M-0033",
    title: "コンベンション棟 空調設備図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-04-05T16:20:00",
    size: "8.9 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c13",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZN3-ZZ-IFC-A-0002",
    title: "マリーナ棟 IFC 統合モデル",
    type: "ifc",
    state: "Shared",
    revision: "P01.02",
    security: "limited",
    naming: "pass",
    owner: "u10",
    org: "南洋建設設計",
    updated: "2026-05-22T11:00:00",
    size: "380 MB",
    ext: "IFC",
    discipline: "意匠",
  },
  {
    id: "c14",
    projectId: "proj-okn",
    identifier: "OKN-STR-ZN1-03-BCF-S-0011",
    title: "3F 柱脚接合部 干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.01",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-25T13:45:00",
    size: "105 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c15",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZZ-ZZ-SP-A-0007",
    title: "外壁・屋根仕様書",
    type: "document",
    state: "Published",
    revision: "C01",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2026-03-30T10:00:00",
    size: "2.3 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c16",
    projectId: "proj-okn",
    identifier: "OKN-ELC-ZN2-ZZ-DR-E-0018",
    title: "コンベンション 電気幹線図",
    type: "drawing",
    state: "WIP",
    revision: "P01.04",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-05-29T17:00:00",
    size: "3.7 MB",
    ext: "PDF",
    discipline: "電気",
  },
  {
    id: "c17",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZN1-RF-DR-A-0088",
    title: "ホテル棟 屋上 詳細図",
    type: "drawing",
    state: "Archived",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u10",
    org: "南洋建設設計",
    updated: "2026-02-14T09:30:00",
    size: "4.0 MB",
    ext: "DWG",
    discipline: "意匠",
  },
  {
    id: "c18",
    projectId: "proj-okn",
    identifier: "okn-mep-zn3-zz-dr-m-04",
    title: "マリーナ 給排水 ドラフト",
    type: "drawing",
    state: "WIP",
    revision: "P01.00",
    security: "limited",
    naming: "fail",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-01T08:00:00",
    size: "2.8 MB",
    ext: "DWG",
    discipline: "設備",
    issue: "小文字使用・連番桁数不足 (4桁必須)",
  },

  // NGY — 名古屋都市高速道路改修工事 (10 containers)
  {
    id: "c19",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC1-ZZ-DR-C-0001",
    title: "第1工区 平面線形図",
    type: "drawing",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-04-20T10:00:00",
    size: "9.1 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c20",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC2-ZZ-DR-C-0022",
    title: "第2工区 橋梁一般図",
    type: "drawing",
    state: "Shared",
    revision: "P05.01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-15T14:00:00",
    size: "7.6 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c21",
    projectId: "proj-ngy",
    identifier: "NGY-STR-SEC1-ZZ-M3-S-0003",
    title: "第1工区 橋脚構造解析モデル",
    type: "model",
    state: "Published",
    revision: "C02",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-04-10T16:30:00",
    size: "192 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c22",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC3-ZZ-IFC-C-0001",
    title: "第3工区 トンネル IFC モデル",
    type: "ifc",
    state: "WIP",
    revision: "P02.02",
    security: "confidential",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-28T11:00:00",
    size: "620 MB",
    ext: "IFC",
    discipline: "土木",
  },
  {
    id: "c23",
    projectId: "proj-ngy",
    identifier: "NGY-STR-SEC2-04-BCF-S-0009",
    title: "4号橋梁 PC桁 干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.02",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-20T09:30:00",
    size: "78 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c24",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-ZZ-ZZ-SP-C-0005",
    title: "道路構造物 設計仕様書",
    type: "document",
    state: "Published",
    revision: "C02",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2026-03-15T13:00:00",
    size: "3.5 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c25",
    projectId: "proj-ngy",
    identifier: "NGY-MEP-SEC1-ZZ-DR-M-0044",
    title: "第1工区 トンネル換気設備図",
    type: "drawing",
    state: "Shared",
    revision: "P02.00",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-05-12T15:00:00",
    size: "6.3 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c26",
    projectId: "proj-ngy",
    identifier: "NGY-ELC-SEC2-ZZ-DR-E-0031",
    title: "第2工区 道路照明設計図",
    type: "drawing",
    state: "WIP",
    revision: "P01.03",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-02T10:00:00",
    size: "4.7 MB",
    ext: "DWG",
    discipline: "電気",
  },
  {
    id: "c27",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC1-ZZ-DR-C-0099",
    title: "第1工区 縦断面図 (旧版)",
    type: "drawing",
    state: "Archived",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-02-01T08:00:00",
    size: "5.5 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c28",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC3-B1-DR-C-07",
    title: "トンネル坑口 ドラフト",
    type: "drawing",
    state: "WIP",
    revision: "P01.00",
    security: "limited",
    naming: "warn",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-05T09:00:00",
    size: "3.2 MB",
    ext: "DWG",
    discipline: "土木",
    issue: "連番桁数不足 (4桁必須)",
  },

  // OSK — 大阪港湾複合施設整備 (10 containers)
  {
    id: "c29",
    projectId: "proj-osk",
    identifier: "OSK-CVL-PH1-ZZ-DR-C-0001",
    title: "護岸改修 標準断面図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-08-10T10:00:00",
    size: "6.0 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c30",
    projectId: "proj-osk",
    identifier: "OSK-ARC-BLK1-01-DR-A-0015",
    title: "物流棟A 1F 平面図",
    type: "drawing",
    state: "Shared",
    revision: "P02.01",
    security: "limited",
    naming: "pass",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-10-22T14:00:00",
    size: "5.8 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c31",
    projectId: "proj-osk",
    identifier: "OSK-STR-BLK1-ZZ-M3-S-0004",
    title: "物流棟A 鉄骨構造モデル",
    type: "model",
    state: "WIP",
    revision: "P03.02",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2025-12-15T09:00:00",
    size: "155 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c32",
    projectId: "proj-osk",
    identifier: "OSK-CVL-PH1-ZZ-IFC-C-0001",
    title: "護岸・埋立 IFC モデル",
    type: "ifc",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-09-30T16:00:00",
    size: "290 MB",
    ext: "IFC",
    discipline: "土木",
  },
  {
    id: "c33",
    projectId: "proj-osk",
    identifier: "OSK-ARC-BLK2-ZZ-DR-A-0028",
    title: "商業棟B 外観パース図",
    type: "drawing",
    state: "Archived",
    revision: "C01",
    security: "public",
    naming: "pass",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-07-20T11:00:00",
    size: "8.4 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c34",
    projectId: "proj-osk",
    identifier: "OSK-MEP-BLK1-ZZ-DR-M-0019",
    title: "物流棟 消火設備平面図",
    type: "drawing",
    state: "Shared",
    revision: "P01.03",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2025-11-08T14:30:00",
    size: "7.1 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c35",
    projectId: "proj-osk",
    identifier: "OSK-STR-BLK2-04-BCF-S-0007",
    title: "4号柱 地盤沈下 干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.01",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2025-12-20T10:00:00",
    size: "64 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c36",
    projectId: "proj-osk",
    identifier: "OSK-CVL-ZZ-ZZ-SP-C-0003",
    title: "地盤改良 設計仕様書",
    type: "document",
    state: "Published",
    revision: "C02",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2025-08-25T13:00:00",
    size: "4.2 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c37",
    projectId: "proj-osk",
    identifier: "OSK-ELC-BLK1-ZZ-DR-E-0024",
    title: "物流棟 受変電設備図",
    type: "drawing",
    state: "WIP",
    revision: "P02.00",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2025-12-28T16:00:00",
    size: "5.0 MB",
    ext: "DWG",
    discipline: "電気",
  },
  {
    id: "c38",
    projectId: "proj-osk",
    identifier: "osk-arc-blk3-zz-dr-a-0",
    title: "公園エリア 平面図 (暫定)",
    type: "drawing",
    state: "WIP",
    revision: "P01.00",
    security: "limited",
    naming: "fail",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-12-31T09:00:00",
    size: "2.0 MB",
    ext: "DWG",
    discipline: "意匠",
    issue: "小文字使用・連番桁数不足 (4桁必須)",
  },

  // SKD — 仙台駅東口再開発計画 (10 containers)
  {
    id: "c39",
    projectId: "proj-skd",
    identifier: "SKD-ARC-ZZ-ZZ-DR-A-0001",
    title: "全体配置計画図",
    type: "drawing",
    state: "Published",
    revision: "C04",
    security: "limited",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2025-12-01T10:00:00",
    size: "7.2 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c40",
    projectId: "proj-skd",
    identifier: "SKD-ARC-TB1-01-DR-A-0055",
    title: "商業棟1 1F 詳細平面図",
    type: "drawing",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2025-11-15T14:00:00",
    size: "6.5 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c41",
    projectId: "proj-skd",
    identifier: "SKD-STR-TB1-ZZ-M3-S-0007",
    title: "商業棟1 構造統合モデル (竣工版)",
    type: "model",
    state: "Archived",
    revision: "C05",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-02-10T09:00:00",
    size: "310 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c42",
    projectId: "proj-skd",
    identifier: "SKD-ARC-ZZ-ZZ-IFC-A-0003",
    title: "全体 IFC 竣工モデル",
    type: "ifc",
    state: "Published",
    revision: "C04",
    security: "limited",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2026-03-01T11:00:00",
    size: "725 MB",
    ext: "IFC",
    discipline: "意匠",
  },
  {
    id: "c43",
    projectId: "proj-skd",
    identifier: "SKD-MEP-TB2-ZZ-DR-M-0038",
    title: "商業棟2 機械設備竣工図",
    type: "drawing",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2025-12-20T16:00:00",
    size: "9.3 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c44",
    projectId: "proj-skd",
    identifier: "SKD-ELC-TB1-ZZ-DR-E-0022",
    title: "商業棟1 電気竣工図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2025-12-18T14:00:00",
    size: "5.5 MB",
    ext: "PDF",
    discipline: "電気",
  },
  {
    id: "c45",
    projectId: "proj-skd",
    identifier: "SKD-CVL-ZZ-ZZ-DR-C-0009",
    title: "歩行者デッキ 構造図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2025-11-30T10:00:00",
    size: "8.1 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c46",
    projectId: "proj-skd",
    identifier: "SKD-ARC-ZZ-ZZ-SP-A-0018",
    title: "外構・景観仕様書 (竣工版)",
    type: "document",
    state: "Published",
    revision: "C03",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2025-12-10T13:00:00",
    size: "3.8 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c47",
    projectId: "proj-skd",
    identifier: "SKD-STR-TB2-05-BCF-S-0031",
    title: "5F スラブ開口 干渉指摘 (解決済)",
    type: "bcf",
    state: "Archived",
    revision: "P02.04",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2025-09-15T09:00:00",
    size: "43 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c48",
    projectId: "proj-skd",
    identifier: "SKD-ARC-ZZ-ZZ-SP-A-0020",
    title: "プロジェクト完了報告書",
    type: "document",
    state: "Published",
    revision: "C01",
    security: "public",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2026-03-31T17:00:00",
    size: "12.7 MB",
    ext: "PDF",
    discipline: "意匠",
  },

  // HKR — 北陸新幹線延伸工事 (13 containers)
  {
    id: "c49",
    projectId: "proj-hkr",
    identifier: "HKR-CVL-ZZ-ZZ-DR-C-0001",
    title: "路線全体配置図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-03-15T10:00:00",
    size: "9.5 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c50",
    projectId: "proj-hkr",
    identifier: "HKR-CVL-TN1-B3-DR-C-0015",
    title: "第1トンネル 標準断面図",
    type: "drawing",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-04-10T14:00:00",
    size: "7.2 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c51",
    projectId: "proj-hkr",
    identifier: "HKR-STR-TN1-ZZ-M3-S-0003",
    title: "第1トンネル 覆工構造解析モデル",
    type: "model",
    state: "Shared",
    revision: "P05.01",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-20T09:00:00",
    size: "342 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c52",
    projectId: "proj-hkr",
    identifier: "HKR-CVL-TN2-B4-DR-C-0022",
    title: "第2トンネル 掘削計画図",
    type: "drawing",
    state: "WIP",
    revision: "P03.02",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-01T11:00:00",
    size: "6.8 MB",
    ext: "DWG",
    discipline: "土木",
  },
  {
    id: "c53",
    projectId: "proj-hkr",
    identifier: "HKR-CVL-BRG-ZZ-DR-C-0008",
    title: "高架橋区間 一般図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-02-28T16:00:00",
    size: "11.3 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c54",
    projectId: "proj-hkr",
    identifier: "HKR-STR-BRG-ZZ-M3-S-0005",
    title: "高架橋 PC桁 構造詳細モデル",
    type: "model",
    state: "Shared",
    revision: "P04.03",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-05T10:00:00",
    size: "287 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c55",
    projectId: "proj-hkr",
    identifier: "HKR-CVL-ZZ-ZZ-IFC-C-0001",
    title: "路線全体 IFC モデル (土木統合)",
    type: "ifc",
    state: "Shared",
    revision: "P02.00",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-12T15:00:00",
    size: "1.2 GB",
    ext: "IFC",
    discipline: "土木",
  },
  {
    id: "c56",
    projectId: "proj-hkr",
    identifier: "HKR-STR-TN1-ZZ-BCF-S-0044",
    title: "第1トンネル セグメント鉄筋 干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.02",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-28T14:00:00",
    size: "5.1 MB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c57",
    projectId: "proj-hkr",
    identifier: "HKR-MEP-TN1-B3-DR-M-0018",
    title: "第1トンネル 換気設備配置図",
    type: "drawing",
    state: "WIP",
    revision: "P02.05",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-05T09:00:00",
    size: "8.4 MB",
    ext: "DWG",
    discipline: "設備",
  },
  {
    id: "c58",
    projectId: "proj-hkr",
    identifier: "HKR-ELC-TN1-ZZ-DR-E-0012",
    title: "トンネル内 非常用照明・防災設備図",
    type: "drawing",
    state: "WIP",
    revision: "P01.03",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-08T11:00:00",
    size: "6.7 MB",
    ext: "DWG",
    discipline: "電気",
  },
  {
    id: "c59",
    projectId: "proj-hkr",
    identifier: "HKR-CVL-TN3-B2-DR-C-0031",
    title: "第3トンネル 坑口部詳細図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-01-20T10:00:00",
    size: "5.9 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c60",
    projectId: "proj-hkr",
    identifier: "HKR-CVL-ZZ-ZZ-SP-C-0002",
    title: "地質調査報告書 (全区間)",
    type: "document",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2025-12-01T16:00:00",
    size: "45.8 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c61",
    projectId: "proj-hkr",
    identifier: "hkr-str-brg-zz-bcf-s-007",
    title: "高架橋 橋脚頭部 接合部 干渉指摘 (暫定)",
    type: "bcf",
    state: "WIP",
    revision: "P01.00",
    security: "limited",
    naming: "fail",
    owner: "u4",
    org: "東和構造",
    updated: "2026-06-10T13:00:00",
    size: "2.3 MB",
    ext: "BCF",
    discipline: "構造",
    issue: "小文字使用・連番桁数不足 (4桁必須)",
  },

  // SWG — 首都高速湾岸線 老朽化対策工事 (13 containers)
  {
    id: "c62",
    projectId: "proj-swg",
    identifier: "SWG-CVL-ZZ-ZZ-DR-C-0001",
    title: "全体工事区間配置図",
    type: "drawing",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-04-01T10:00:00",
    size: "8.7 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c63",
    projectId: "proj-swg",
    identifier: "SWG-STR-ZN1-ZZ-DR-S-0011",
    title: "第1工区 橋脚耐震補強 断面図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-03-20T14:00:00",
    size: "6.4 MB",
    ext: "PDF",
    discipline: "構造",
  },
  {
    id: "c64",
    projectId: "proj-swg",
    identifier: "SWG-STR-ZN1-ZZ-M3-S-0004",
    title: "第1工区 橋梁構造解析モデル",
    type: "model",
    state: "Shared",
    revision: "P06.01",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-15T09:00:00",
    size: "198 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c65",
    projectId: "proj-swg",
    identifier: "SWG-CVL-ZN2-ZZ-DR-C-0019",
    title: "第2工区 橋桁取替工事 施工図",
    type: "drawing",
    state: "WIP",
    revision: "P04.02",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-03T11:00:00",
    size: "9.1 MB",
    ext: "DWG",
    discipline: "土木",
  },
  {
    id: "c66",
    projectId: "proj-swg",
    identifier: "SWG-STR-ZN2-ZZ-M3-S-0006",
    title: "第2工区 新設PC桁 詳細モデル",
    type: "model",
    state: "WIP",
    revision: "P03.04",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-06-07T15:00:00",
    size: "224 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c67",
    projectId: "proj-swg",
    identifier: "SWG-ARC-ZN3-ZZ-DR-A-0007",
    title: "第3工区 防音壁改修 意匠図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u3",
    org: "大成設計",
    updated: "2026-02-10T10:00:00",
    size: "4.2 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c68",
    projectId: "proj-swg",
    identifier: "SWG-CVL-ZZ-ZZ-IFC-C-0002",
    title: "全体 IFC 工事統合モデル",
    type: "ifc",
    state: "Shared",
    revision: "P02.01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-22T14:00:00",
    size: "876 MB",
    ext: "IFC",
    discipline: "土木",
  },
  {
    id: "c69",
    projectId: "proj-swg",
    identifier: "SWG-STR-ZN1-ZZ-BCF-S-0015",
    title: "第1工区 主桁腐食・断面欠損 指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.03",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-30T11:00:00",
    size: "3.8 MB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c70",
    projectId: "proj-swg",
    identifier: "SWG-MEP-ZN2-ZZ-DR-M-0009",
    title: "第2工区 排水設備改修図",
    type: "drawing",
    state: "WIP",
    revision: "P02.01",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-08T09:00:00",
    size: "5.3 MB",
    ext: "DWG",
    discipline: "設備",
  },
  {
    id: "c71",
    projectId: "proj-swg",
    identifier: "SWG-ELC-ZZ-ZZ-DR-E-0003",
    title: "照明・監視カメラ改修図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-01-15T16:00:00",
    size: "4.7 MB",
    ext: "PDF",
    discipline: "電気",
  },
  {
    id: "c72",
    projectId: "proj-swg",
    identifier: "SWG-CVL-ZN3-ZZ-DR-C-0025",
    title: "第3工区 舗装打替計画図",
    type: "drawing",
    state: "Shared",
    revision: "P02.00",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-04-20T14:00:00",
    size: "7.6 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c73",
    projectId: "proj-swg",
    identifier: "SWG-STR-ZZ-ZZ-SP-S-0001",
    title: "耐震補強設計要領書",
    type: "document",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2025-11-30T10:00:00",
    size: "18.2 MB",
    ext: "PDF",
    discipline: "構造",
  },
  {
    id: "c74",
    projectId: "proj-swg",
    identifier: "SWG-CVL-ZN1-ZZ-BCF-C-0028",
    title: "第1工区 鋼板巻立て 工法調整指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-01T10:00:00",
    size: "2.9 MB",
    ext: "BCF",
    discipline: "土木",
  },

  // KSH — 九州縦貫道路 未整備区間整備 (13 containers)
  {
    id: "c75",
    projectId: "proj-ksh",
    identifier: "KSH-CVL-ZZ-ZZ-DR-C-0001",
    title: "路線全体計画図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-03-01T10:00:00",
    size: "10.2 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c76",
    projectId: "proj-ksh",
    identifier: "KSH-CVL-SEC1-ZZ-DR-C-0018",
    title: "第1工区 切土・盛土 横断図集",
    type: "drawing",
    state: "Shared",
    revision: "P03.01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-10T14:00:00",
    size: "14.5 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c77",
    projectId: "proj-ksh",
    identifier: "KSH-STR-SEC1-ZZ-M3-S-0003",
    title: "第1工区 橋梁 RC構造モデル",
    type: "model",
    state: "WIP",
    revision: "P04.02",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-06-08T09:00:00",
    size: "176 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c78",
    projectId: "proj-ksh",
    identifier: "KSH-CVL-SEC2-B2-DR-C-0029",
    title: "第2工区 山岳トンネル 標準断面図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-02-15T11:00:00",
    size: "6.1 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c79",
    projectId: "proj-ksh",
    identifier: "KSH-STR-SEC2-ZZ-M3-S-0007",
    title: "第2工区 RC覆工 構造解析モデル",
    type: "model",
    state: "Shared",
    revision: "P03.00",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-25T15:00:00",
    size: "258 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c80",
    projectId: "proj-ksh",
    identifier: "KSH-CVL-ZZ-ZZ-IFC-C-0001",
    title: "路線 IFC モデル (第1・第2工区統合)",
    type: "ifc",
    state: "Shared",
    revision: "P01.03",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-18T10:00:00",
    size: "948 MB",
    ext: "IFC",
    discipline: "土木",
  },
  {
    id: "c81",
    projectId: "proj-ksh",
    identifier: "KSH-ARC-ZZ-ZZ-DR-A-0004",
    title: "SA/PA 建築 平面図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u3",
    org: "大成設計",
    updated: "2026-01-30T10:00:00",
    size: "4.8 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c82",
    projectId: "proj-ksh",
    identifier: "KSH-MEP-ZZ-ZZ-DR-M-0006",
    title: "SA/PA 給排水・電気設備図",
    type: "drawing",
    state: "Shared",
    revision: "P02.01",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-04-15T14:00:00",
    size: "5.6 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c83",
    projectId: "proj-ksh",
    identifier: "KSH-ELC-SEC1-ZZ-DR-E-0010",
    title: "道路照明・電光掲示板 設備図",
    type: "drawing",
    state: "WIP",
    revision: "P01.04",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-05T11:00:00",
    size: "7.3 MB",
    ext: "DWG",
    discipline: "電気",
  },
  {
    id: "c84",
    projectId: "proj-ksh",
    identifier: "KSH-CVL-SEC2-ZZ-BCF-C-0033",
    title: "第2工区 擁壁基礎 地盤干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.00",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-06T10:00:00",
    size: "3.4 MB",
    ext: "BCF",
    discipline: "土木",
  },
  {
    id: "c85",
    projectId: "proj-ksh",
    identifier: "KSH-STR-SEC1-ZZ-BCF-S-0018",
    title: "第1工区 PC橋梁 設計変更 指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.01",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-06-09T14:00:00",
    size: "4.1 MB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c86",
    projectId: "proj-ksh",
    identifier: "KSH-CVL-ZZ-ZZ-SP-C-0003",
    title: "環境影響評価 施工中モニタリング報告",
    type: "document",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-01T10:00:00",
    size: "28.5 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c87",
    projectId: "proj-ksh",
    identifier: "ksh-cvl-sec3-zz-dr-c-0",
    title: "第3工区 仮設計画図 (暫定版)",
    type: "drawing",
    state: "WIP",
    revision: "P01.00",
    security: "limited",
    naming: "fail",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-12T09:00:00",
    size: "3.2 MB",
    ext: "DWG",
    discipline: "土木",
    issue: "小文字使用・連番桁数不足 (4桁必須)",
  },

  // HND — 羽田空港 第4旅客ターミナル整備 (13 containers)
  {
    id: "c88",
    projectId: "proj-hnd",
    identifier: "HND-ARC-ZZ-ZZ-DR-A-0001",
    title: "ターミナル全体 配置・外観計画図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u1",
    org: "大成設計",
    updated: "2026-04-15T10:00:00",
    size: "12.4 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c89",
    projectId: "proj-hnd",
    identifier: "HND-ARC-T4-01-DR-A-0051",
    title: "1F 旅客ホール 平面詳細図",
    type: "drawing",
    state: "Shared",
    revision: "P03.02",
    security: "limited",
    naming: "pass",
    owner: "u3",
    org: "大成設計",
    updated: "2026-05-28T14:00:00",
    size: "8.9 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c90",
    projectId: "proj-hnd",
    identifier: "HND-ARC-T4-02-DR-A-0063",
    title: "2F 出発ロビー 平面詳細図",
    type: "drawing",
    state: "WIP",
    revision: "P04.01",
    security: "limited",
    naming: "pass",
    owner: "u3",
    org: "大成設計",
    updated: "2026-06-10T09:00:00",
    size: "9.2 MB",
    ext: "DWG",
    discipline: "意匠",
  },
  {
    id: "c91",
    projectId: "proj-hnd",
    identifier: "HND-STR-T4-ZZ-M3-S-0009",
    title: "ターミナル全体 構造解析モデル",
    type: "model",
    state: "WIP",
    revision: "P05.03",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-06-12T15:00:00",
    size: "489 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c92",
    projectId: "proj-hnd",
    identifier: "HND-MEP-T4-ZZ-DR-M-0044",
    title: "空調・換気設備 全体系統図",
    type: "drawing",
    state: "WIP",
    revision: "P03.05",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-11T11:00:00",
    size: "11.8 MB",
    ext: "DWG",
    discipline: "設備",
  },
  {
    id: "c93",
    projectId: "proj-hnd",
    identifier: "HND-MEP-T4-ZZ-DR-M-0055",
    title: "給排水衛生 設備図",
    type: "drawing",
    state: "WIP",
    revision: "P02.04",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-09T14:00:00",
    size: "9.4 MB",
    ext: "DWG",
    discipline: "設備",
  },
  {
    id: "c94",
    projectId: "proj-hnd",
    identifier: "HND-ELC-T4-ZZ-DR-E-0022",
    title: "電気設備 幹線・受変電 系統図",
    type: "drawing",
    state: "Shared",
    revision: "P02.01",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-05-20T10:00:00",
    size: "7.1 MB",
    ext: "PDF",
    discipline: "電気",
  },
  {
    id: "c95",
    projectId: "proj-hnd",
    identifier: "HND-ARC-T4-ZZ-IFC-A-0003",
    title: "ターミナル IFC 統合モデル (意匠+構造+設備)",
    type: "ifc",
    state: "Shared",
    revision: "P02.00",
    security: "limited",
    naming: "pass",
    owner: "u1",
    org: "大成設計",
    updated: "2026-06-01T09:00:00",
    size: "1.8 GB",
    ext: "IFC",
    discipline: "意匠",
  },
  {
    id: "c96",
    projectId: "proj-hnd",
    identifier: "HND-STR-T4-ZZ-BCF-S-0081",
    title: "ターミナル 屋根柱脚 梁取合い 干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.04",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-06-07T14:00:00",
    size: "6.7 MB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c97",
    projectId: "proj-hnd",
    identifier: "HND-MEP-T4-03-DR-M-0038",
    title: "3F 機械室 配管詳細図",
    type: "drawing",
    state: "WIP",
    revision: "P02.02",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-13T09:00:00",
    size: "8.3 MB",
    ext: "DWG",
    discipline: "設備",
  },
  {
    id: "c98",
    projectId: "proj-hnd",
    identifier: "HND-ARC-T4-B1-DR-A-0025",
    title: "B1F 商業施設 平面図",
    type: "drawing",
    state: "Shared",
    revision: "P02.03",
    security: "limited",
    naming: "pass",
    owner: "u3",
    org: "大成設計",
    updated: "2026-05-15T11:00:00",
    size: "7.5 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c99",
    projectId: "proj-hnd",
    identifier: "HND-CVL-ZZ-ZZ-DR-C-0007",
    title: "エプロン・駐機スポット 舗装計画図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-03-10T10:00:00",
    size: "13.2 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c100",
    projectId: "proj-hnd",
    identifier: "HND-ARC-ZZ-ZZ-SP-A-0001",
    title: "設計概要説明書・機能要件一覧",
    type: "document",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u1",
    org: "大成設計",
    updated: "2026-02-28T16:00:00",
    size: "22.1 MB",
    ext: "PDF",
    discipline: "意匠",
  },

  // TWG — 東京湾岸防潮堤 耐震・耐水強化事業 (13 containers)
  {
    id: "c101",
    projectId: "proj-twg",
    identifier: "TWG-CVL-ZZ-ZZ-DR-C-0001",
    title: "防潮堤全体配置図",
    type: "drawing",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-03-20T10:00:00",
    size: "11.8 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c102",
    projectId: "proj-twg",
    identifier: "TWG-CVL-SEC1-ZZ-DR-C-0014",
    title: "第1工区 堤体 標準断面図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-02-10T11:00:00",
    size: "7.4 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c103",
    projectId: "proj-twg",
    identifier: "TWG-STR-SEC1-ZZ-M3-S-0004",
    title: "第1工区 堤体 構造解析モデル (液状化対策含む)",
    type: "model",
    state: "Shared",
    revision: "P04.01",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-08T09:00:00",
    size: "312 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c104",
    projectId: "proj-twg",
    identifier: "TWG-CVL-SEC2-ZZ-DR-C-0021",
    title: "第2工区 護岸改修 断面詳細図",
    type: "drawing",
    state: "Shared",
    revision: "P03.02",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-04-25T14:00:00",
    size: "8.6 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c105",
    projectId: "proj-twg",
    identifier: "TWG-CVL-ZZ-ZZ-IFC-C-0001",
    title: "防潮堤全体 IFC モデル (全工区統合)",
    type: "ifc",
    state: "Shared",
    revision: "P02.02",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-30T15:00:00",
    size: "1.1 GB",
    ext: "IFC",
    discipline: "土木",
  },
  {
    id: "c106",
    projectId: "proj-twg",
    identifier: "TWG-STR-SEC1-ZZ-BCF-S-0009",
    title: "第1工区 鋼矢板継手 設計干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.02",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-06-04T11:00:00",
    size: "2.8 MB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c107",
    projectId: "proj-twg",
    identifier: "TWG-CVL-SEC3-ZZ-DR-C-0033",
    title: "第3工区 堤防嵩上げ 計画図",
    type: "drawing",
    state: "WIP",
    revision: "P02.03",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-09T10:00:00",
    size: "9.0 MB",
    ext: "DWG",
    discipline: "土木",
  },
  {
    id: "c108",
    projectId: "proj-twg",
    identifier: "TWG-STR-SEC2-ZZ-M3-S-0007",
    title: "第2工区 ケーソン構造 詳細モデル",
    type: "model",
    state: "Shared",
    revision: "P03.01",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-12T09:00:00",
    size: "241 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c109",
    projectId: "proj-twg",
    identifier: "TWG-MEP-ZZ-ZZ-DR-M-0005",
    title: "排水ポンプ設備 配置・系統図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-01-25T16:00:00",
    size: "5.2 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c110",
    projectId: "proj-twg",
    identifier: "TWG-ELC-ZZ-ZZ-DR-E-0003",
    title: "防災無線・潮位計 監視設備図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-02-05T10:00:00",
    size: "4.1 MB",
    ext: "PDF",
    discipline: "電気",
  },
  {
    id: "c111",
    projectId: "proj-twg",
    identifier: "TWG-CVL-ZZ-ZZ-SP-C-0004",
    title: "地盤調査・液状化リスク評価報告書",
    type: "document",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2025-10-15T10:00:00",
    size: "35.7 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c112",
    projectId: "proj-twg",
    identifier: "TWG-CVL-SEC1-ZZ-DR-C-0044",
    title: "第1工区 仮締切・掘削計画図",
    type: "drawing",
    state: "WIP",
    revision: "P01.05",
    security: "limited",
    naming: "warn",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-13T11:00:00",
    size: "6.3 MB",
    ext: "DWG",
    discipline: "土木",
    issue: "Volume SEC1 のレベルコード要確認",
  },
  {
    id: "c113",
    projectId: "proj-twg",
    identifier: "twg-cvl-sec4-zz-dr-c-0",
    title: "第4工区 暫定計画図 (作成中)",
    type: "drawing",
    state: "WIP",
    revision: "P01.00",
    security: "limited",
    naming: "fail",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-14T08:00:00",
    size: "1.8 MB",
    ext: "DWG",
    discipline: "土木",
    issue: "小文字使用・連番桁数不足 (4桁必須)",
  },
];

/** Group containers by projectId for easy lookup */
export const containersByProject: Record<string, DemoContainer[]> = {};
for (const c of demoContainers) {
  if (!containersByProject[c.projectId]) containersByProject[c.projectId] = [];
  containersByProject[c.projectId].push(c);
}

// ---------------------------------------------------------------------------
// InformationContainers (mapped from demoContainers)
// ---------------------------------------------------------------------------

export const demoInformationContainers: InformationContainer[] =
  demoContainers.map((container) => ({
    id: container.id,
    project_id: container.projectId,
    identifier: container.identifier,
    title: container.title,
    container_type: container.type,
    current_state: container.state,
    current_revision: container.revision,
    current_branch: null,
    security_level: container.security,
    naming_valid: container.naming === "pass",
    naming_issues: container.issue ?? null,
    created_by: container.owner,
    created_at: container.updated,
    updated_at: container.updated,
  }));

// ---------------------------------------------------------------------------
// Approvals (10 items)
// ---------------------------------------------------------------------------

export const approvals = [
  {
    id: "a1",
    containerId: "c2",
    identifier: "TKO-STR-XX-ZZ-M3-S-0008",
    title: "全体構造解析モデル v8",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u4",
    requestedAt: "2026-05-30T09:14:00Z",
    due: "2026-06-02",
    priority: "high",
    security: "confidential",
    projectId: "demo",
  },
  {
    id: "a2",
    containerId: "c6",
    identifier: "TKO-STR-XX-03-BCF-S-0044",
    title: "3F 梁貫通スリーブ干渉 指摘",
    stage: "check / review / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u4",
    requestedAt: "2026-05-28T14:22:00Z",
    due: "2026-05-31",
    priority: "high",
    security: "limited",
    projectId: "demo",
  },
  {
    id: "a3",
    containerId: "c1",
    identifier: "TKO-ARC-XX-07-DR-A-0421",
    title: "基準階平面詳細図 (7F オフィス)",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u3",
    requestedAt: "2026-05-29T11:05:00Z",
    due: "2026-06-01",
    priority: "medium",
    security: "limited",
    projectId: "demo",
  },
  {
    id: "a4",
    containerId: "c10",
    identifier: "OKN-ARC-ZN1-01-DR-A-0042",
    title: "ホテル棟 1F ロビー平面詳細図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u10",
    requestedAt: "2026-06-01T08:30:00Z",
    due: "2026-06-10",
    priority: "medium",
    security: "limited",
    projectId: "proj-okn",
  },
  {
    id: "a5",
    containerId: "c13",
    identifier: "OKN-ARC-ZN3-ZZ-IFC-A-0002",
    title: "マリーナ棟 IFC 統合モデル",
    stage: "check / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u10",
    requestedAt: "2026-06-02T16:45:00Z",
    due: "2026-06-15",
    priority: "high",
    security: "limited",
    projectId: "proj-okn",
  },
  {
    id: "a6",
    containerId: "c20",
    identifier: "NGY-CVL-SEC2-ZZ-DR-C-0022",
    title: "第2工区 橋梁一般図",
    stage: "review / authorise",
    from: "Shared",
    to: "Published",
    requestedBy: "u7",
    requestedAt: "2026-05-31T13:10:00Z",
    due: "2026-06-08",
    priority: "high",
    security: "limited",
    projectId: "proj-ngy",
  },
  {
    id: "a7",
    containerId: "c23",
    identifier: "NGY-STR-SEC2-04-BCF-S-0009",
    title: "4号橋梁 PC桁 干渉指摘",
    stage: "check / review / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u4",
    requestedAt: "2026-05-30T10:20:00Z",
    due: "2026-06-05",
    priority: "medium",
    security: "limited",
    projectId: "proj-ngy",
  },
  {
    id: "a8",
    containerId: "c30",
    identifier: "OSK-ARC-BLK1-01-DR-A-0015",
    title: "物流棟A 1F 平面図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u8",
    requestedAt: "2026-06-03T09:00:00Z",
    due: "2026-06-20",
    priority: "low",
    security: "limited",
    projectId: "proj-osk",
  },
  {
    id: "a9",
    containerId: "c34",
    identifier: "OSK-MEP-BLK1-ZZ-DR-M-0019",
    title: "物流棟 消火設備平面図",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u5",
    requestedAt: "2026-06-04T15:30:00Z",
    due: "2026-06-25",
    priority: "medium",
    security: "limited",
    projectId: "proj-osk",
  },
  {
    id: "a10",
    containerId: "c43",
    identifier: "SKD-MEP-TB2-ZZ-DR-M-0038",
    title: "商業棟2 機械設備竣工図",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u5",
    requestedAt: "2026-01-10T11:00:00Z",
    due: "2026-01-15",
    priority: "high",
    security: "limited",
    projectId: "proj-skd",
  },
  // --- HKR: 北陸新幹線延伸工事 ---
  {
    id: "a11",
    containerId: "c49",
    identifier: "HKR-CVL-TN1-ZZ-DR-C-0001",
    title: "第1トンネル 標準断面図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u4",
    requestedAt: "2026-06-10T09:00:00Z",
    due: "2026-07-10",
    priority: "high",
    security: "confidential",
    projectId: "proj-hkr",
  },
  {
    id: "a12",
    containerId: "c51",
    identifier: "HKR-STR-TN1-ZZ-M3-S-0003",
    title: "第1トンネル 構造解析モデル v3",
    stage: "check / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u4",
    requestedAt: "2026-06-12T10:30:00Z",
    due: "2026-07-20",
    priority: "high",
    security: "confidential",
    projectId: "proj-hkr",
  },
  {
    id: "a13",
    containerId: "c55",
    identifier: "HKR-ARC-ZZ-ZZ-IFC-A-0001",
    title: "北陸延伸 統合 IFC モデル",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u6",
    requestedAt: "2026-06-15T11:00:00Z",
    due: "2026-08-01",
    priority: "high",
    security: "limited",
    projectId: "proj-hkr",
  },
  {
    id: "a14",
    containerId: "c56",
    identifier: "HKR-STR-TN2-ZZ-BCF-S-0012",
    title: "第2トンネル 補強鉄筋 干渉指摘",
    stage: "check / review / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u4",
    requestedAt: "2026-06-08T14:00:00Z",
    due: "2026-07-15",
    priority: "medium",
    security: "limited",
    projectId: "proj-hkr",
  },
  // --- SWG: 首都高速湾岸線 老朽化対策 ---
  {
    id: "a15",
    containerId: "c62",
    identifier: "SWG-CVL-BRG-ZZ-DR-C-0001",
    title: "橋梁補修設計図 (1号橋)",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u7",
    requestedAt: "2026-06-05T09:30:00Z",
    due: "2026-06-28",
    priority: "high",
    security: "limited",
    projectId: "proj-swg",
  },
  {
    id: "a16",
    containerId: "c65",
    identifier: "SWG-STR-BRG-ZZ-M3-S-0002",
    title: "桁補強 3D 構造モデル",
    stage: "check / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u4",
    requestedAt: "2026-06-07T13:00:00Z",
    due: "2026-07-05",
    priority: "high",
    security: "limited",
    projectId: "proj-swg",
  },
  {
    id: "a17",
    containerId: "c69",
    identifier: "SWG-ARC-ZZ-ZZ-IFC-A-0001",
    title: "湾岸線 統合 IFC モデル",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u6",
    requestedAt: "2026-06-09T15:00:00Z",
    due: "2026-07-15",
    priority: "medium",
    security: "limited",
    projectId: "proj-swg",
  },
  // --- KSH: 九州縦貫道路 ---
  {
    id: "a18",
    containerId: "c75",
    identifier: "KSH-CVL-ZZ-ZZ-DR-C-0011",
    title: "道路線形一般図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u7",
    requestedAt: "2026-06-11T08:30:00Z",
    due: "2026-07-25",
    priority: "high",
    security: "limited",
    projectId: "proj-ksh",
  },
  {
    id: "a19",
    containerId: "c80",
    identifier: "KSH-STR-ZZ-ZZ-M3-S-0002",
    title: "本線橋梁 構造モデル",
    stage: "check / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u4",
    requestedAt: "2026-06-13T10:00:00Z",
    due: "2026-08-10",
    priority: "medium",
    security: "limited",
    projectId: "proj-ksh",
  },
  {
    id: "a20",
    containerId: "c83",
    identifier: "KSH-ARC-ZZ-ZZ-IFC-A-0001",
    title: "九州縦貫道 統合 IFC モデル",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u6",
    requestedAt: "2026-06-14T11:30:00Z",
    due: "2026-08-20",
    priority: "medium",
    security: "limited",
    projectId: "proj-ksh",
  },
  // --- HND: 羽田空港 第4旅客ターミナル ---
  {
    id: "a21",
    containerId: "c88",
    identifier: "HND-ARC-T4-ZZ-DR-A-0001",
    title: "ターミナル棟 基本平面図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u3",
    requestedAt: "2026-06-16T09:00:00Z",
    due: "2026-07-01",
    priority: "high",
    security: "confidential",
    projectId: "proj-hnd",
  },
  {
    id: "a22",
    containerId: "c91",
    identifier: "HND-MEP-T4-ZZ-DR-M-0009",
    title: "旅客ターミナル 空調・換気設備図",
    stage: "check / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u5",
    requestedAt: "2026-06-17T10:00:00Z",
    due: "2026-07-10",
    priority: "high",
    security: "limited",
    projectId: "proj-hnd",
  },
  {
    id: "a23",
    containerId: "c94",
    identifier: "HND-ARC-T4-ZZ-IFC-A-0001",
    title: "T4 統合 IFC モデル (建築+構造)",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u6",
    requestedAt: "2026-06-10T14:30:00Z",
    due: "2026-07-20",
    priority: "high",
    security: "limited",
    projectId: "proj-hnd",
  },
  {
    id: "a24",
    containerId: "c97",
    identifier: "HND-ELC-T4-ZZ-DR-E-0007",
    title: "T4 電力幹線図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u5",
    requestedAt: "2026-06-11T15:00:00Z",
    due: "2026-06-30",
    priority: "medium",
    security: "limited",
    projectId: "proj-hnd",
  },
  // --- TWG: 東京湾岸防潮堤 ---
  {
    id: "a25",
    containerId: "c101",
    identifier: "TWG-CVL-ZZ-ZZ-DR-C-0001",
    title: "防潮堤 盛土標準断面図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u7",
    requestedAt: "2026-06-12T09:00:00Z",
    due: "2026-06-20",
    priority: "high",
    security: "confidential",
    projectId: "proj-twg",
  },
  {
    id: "a26",
    containerId: "c103",
    identifier: "TWG-STR-ZZ-ZZ-M3-S-0001",
    title: "防潮堤 構造モデル (全区間)",
    stage: "check / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u4",
    requestedAt: "2026-06-13T11:00:00Z",
    due: "2026-06-25",
    priority: "high",
    security: "limited",
    projectId: "proj-twg",
  },
  {
    id: "a27",
    containerId: "c107",
    identifier: "TWG-MEP-ZZ-ZZ-DR-M-0004",
    title: "排水ポンプ設備 配管図",
    stage: "check / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u5",
    requestedAt: "2026-06-14T13:00:00Z",
    due: "2026-07-01",
    priority: "medium",
    security: "limited",
    projectId: "proj-twg",
  },
  {
    id: "a28",
    containerId: "c105",
    identifier: "TWG-ARC-ZZ-ZZ-IFC-A-0001",
    title: "防潮堤 統合 IFC モデル",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u6",
    requestedAt: "2026-06-15T09:30:00Z",
    due: "2026-07-10",
    priority: "high",
    security: "limited",
    projectId: "proj-twg",
  },
  {
    id: "a29",
    containerId: "c108",
    identifier: "TWG-ELC-ZZ-ZZ-DR-E-0003",
    title: "水位監視システム 電気図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u5",
    requestedAt: "2026-06-16T10:30:00Z",
    due: "2026-07-05",
    priority: "medium",
    security: "limited",
    projectId: "proj-twg",
  },
  {
    id: "a30",
    containerId: "c110",
    identifier: "TWG-CVL-ZZ-ZZ-SP-C-0001",
    title: "耐震・耐水強化設計仕様書",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u6",
    requestedAt: "2026-06-17T08:00:00Z",
    due: "2026-06-15",
    priority: "high",
    security: "confidential",
    projectId: "proj-twg",
  },
] as const;

// ---------------------------------------------------------------------------
// Requirement documents (5 entries)
// ---------------------------------------------------------------------------

export const reqDocs = [
  {
    id: "d1",
    type: "EIR",
    title: "発注者情報要求事項 (EIR) — 東京中央ターミナル",
    revision: "C02",
    status: "approved",
    owner: "u6",
    items: 24,
    desc: "設計・施工各段階で要求する情報、フォーマット、提出時点を定義。",
  },
  {
    id: "d2",
    type: "BEP",
    title: "BIM実行計画書 (BEP) — 設計段階",
    revision: "P03.01",
    status: "review",
    owner: "u1",
    items: 38,
    desc: "情報生成の方針、責任分担、ソフト構成、座標系、品質保証を規定。",
  },
  {
    id: "d3",
    type: "MIDP",
    title: "マスター情報配信計画",
    revision: "P02.00",
    status: "review",
    owner: "u2",
    items: 52,
    desc: "全TIDPを統合した成果物提出スケジュール。",
  },
  {
    id: "d4",
    type: "EIR",
    title: "発注者情報要求事項 (EIR) — 沖縄国際観光リゾート整備",
    revision: "C01",
    status: "approved",
    owner: "u10",
    items: 18,
    desc: "沖縄リゾートプロジェクトにおけるBIM情報要件。環境・景観配慮要求を含む。",
  },
  {
    id: "d5",
    type: "BEP",
    title: "BIM実行計画書 (BEP) — 名古屋都市高速道路改修",
    revision: "P01.02",
    status: "review",
    owner: "u7",
    items: 29,
    desc: "道路・橋梁・トンネルに対応したBIM実行計画。点検・維持管理連携を含む。",
  },
] as const;

// ---------------------------------------------------------------------------
// Requirement items
// ---------------------------------------------------------------------------

export const requirementItems = [
  {
    no: "EIR-01",
    what: "各階平面図 (LOD300)",
    when: "Stage 4 完了時",
    how: "PDF + IFC2x3 / 命名規則準拠",
    who: "発注者・施工者",
    status: "met",
  },
  {
    no: "EIR-02",
    what: "統合構造解析モデル",
    when: "実施設計中間",
    how: "RVT + IFC4 / 座標系JGD2011",
    who: "構造監理",
    status: "met",
  },
  {
    no: "EIR-03",
    what: "設備統合モデル (機械/電気)",
    when: "実施設計完了",
    how: "RVT + COBie",
    who: "FM・施工者",
    status: "partial",
  },
  {
    no: "EIR-04",
    what: "竣工モデル (As-built)",
    when: "引渡時",
    how: "IFC4 + COBie / FM連携",
    who: "資産管理者",
    status: "open",
  },
] as const;

// ---------------------------------------------------------------------------
// Naming segments
// ---------------------------------------------------------------------------

export const namingSegments = [
  { key: "Project", label: "プロジェクト", ex: "TKO" },
  { key: "Originator", label: "発信者", ex: "ARC" },
  { key: "Volume", label: "区分/系統", ex: "XX" },
  { key: "Level", label: "レベル", ex: "07" },
  { key: "Type", label: "種別", ex: "DR" },
  { key: "Role", label: "ロール", ex: "A" },
  { key: "Number", label: "連番", ex: "0001" },
] as const;

// ---------------------------------------------------------------------------
// Audit logs — two representations
//
// `auditLogs` uses the AuditLog API type (for mockRouter / API responses).
// `auditSamples` uses the legacy display shape that AuditLogsPage expects as
//   its fallback (fields: at, actor, event, target, type, op, result, ip, reason).
// ---------------------------------------------------------------------------

export const auditLogs: AuditLog[] = [
  {
    id: "e1",
    occurred_at: "2026-06-14T09:22:18",
    event_type: "container.transition",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "コンテナ",
    target_id: "TKO-ARC-XX-07-DR-A-0421",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e2",
    occurred_at: "2026-06-13T16:48:40",
    event_type: "container.transition",
    actor_id: "u4",
    actor_ip: "10.4.21.40",
    target_type: "コンテナ",
    target_id: "TKO-STR-XX-ZZ-M3-S-0008",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e3",
    occurred_at: "2026-06-13T14:20:55",
    event_type: "approval.act",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "承認",
    target_id: "TKO-ARC-XX-01-DR-A-0205",
    operation: "レビュー承認",
    result: "success",
    reason: null,
  },
  {
    id: "e4",
    occurred_at: "2026-06-13T11:58:31",
    event_type: "security.share",
    actor_id: "u2",
    actor_ip: "10.4.21.51",
    target_type: "外部共有",
    target_id: "TKO-ARC-XX-ZZ-IFC-A-0003",
    operation: "外部共有申請",
    result: "denied",
    reason: "機密区分の承認者不足",
  },
  {
    id: "e5",
    occurred_at: "2026-06-12T18:03:12",
    event_type: "container.naming.fail",
    actor_id: "u3",
    actor_ip: "10.4.21.88",
    target_type: "コンテナ",
    target_id: "tko-arc-xx-12-dr-a-09",
    operation: "命名規則検証",
    result: "warning",
    reason: "連番桁数不足・小文字使用",
  },
  {
    id: "e6",
    occurred_at: "2026-06-12T10:30:00",
    event_type: "container.create",
    actor_id: "u10",
    actor_ip: "10.8.1.22",
    target_type: "コンテナ",
    target_id: "OKN-ARC-ZN1-01-DR-A-0042",
    operation: "コンテナ新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e7",
    occurred_at: "2026-06-11T14:15:44",
    event_type: "container.transition",
    actor_id: "u10",
    actor_ip: "10.8.1.22",
    target_type: "コンテナ",
    target_id: "OKN-ARC-ZN1-ZZ-DR-A-0001",
    operation: "Shared→Published",
    result: "success",
    reason: null,
  },
  {
    id: "e8",
    occurred_at: "2026-06-11T09:00:00",
    event_type: "user.login",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "ユーザー",
    target_id: "u7",
    operation: "ログイン",
    result: "success",
    reason: null,
  },
  {
    id: "e9",
    occurred_at: "2026-06-10T16:44:33",
    event_type: "container.naming.warn",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "NGY-CVL-SEC3-B1-DR-C-07",
    operation: "命名規則検証",
    result: "warning",
    reason: "連番桁数不足 (4桁必須)",
  },
  {
    id: "e10",
    occurred_at: "2026-06-10T13:22:10",
    event_type: "approval.request",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "承認",
    target_id: "NGY-CVL-SEC2-ZZ-DR-C-0022",
    operation: "承認申請",
    result: "success",
    reason: null,
  },
  {
    id: "e11",
    occurred_at: "2026-06-09T15:05:20",
    event_type: "container.update",
    actor_id: "u4",
    actor_ip: "10.4.21.40",
    target_type: "コンテナ",
    target_id: "NGY-STR-SEC1-ZZ-M3-S-0003",
    operation: "コンテナ改訂",
    result: "success",
    reason: null,
  },
  {
    id: "e12",
    occurred_at: "2026-06-09T11:30:00",
    event_type: "security.classification",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "セキュリティ",
    target_id: "OSK-STR-BLK1-ZZ-M3-S-0004",
    operation: "機密区分変更",
    result: "success",
    reason: "設計完了に伴い confidential → limited に緩和",
  },
  {
    id: "e13",
    occurred_at: "2026-06-08T17:48:00",
    event_type: "container.naming.fail",
    actor_id: "u8",
    actor_ip: "10.15.2.44",
    target_type: "コンテナ",
    target_id: "osk-arc-blk3-zz-dr-a-0",
    operation: "命名規則検証",
    result: "warning",
    reason: "小文字使用・連番桁数不足",
  },
  {
    id: "e14",
    occurred_at: "2026-06-08T10:12:05",
    event_type: "container.transition",
    actor_id: "u8",
    actor_ip: "10.15.2.44",
    target_type: "コンテナ",
    target_id: "OSK-CVL-PH1-ZZ-DR-C-0001",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e15",
    occurred_at: "2026-06-07T14:00:00",
    event_type: "project.create",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "プロジェクト",
    target_id: "proj-okn",
    operation: "プロジェクト新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e16",
    occurred_at: "2026-06-06T09:30:00",
    event_type: "user.login",
    actor_id: "u9",
    actor_ip: "10.22.5.9",
    target_type: "ユーザー",
    target_id: "u9",
    operation: "ログイン",
    result: "success",
    reason: null,
  },
  {
    id: "e17",
    occurred_at: "2026-06-05T16:20:00",
    event_type: "container.archive",
    actor_id: "u9",
    actor_ip: "10.22.5.9",
    target_type: "コンテナ",
    target_id: "SKD-STR-TB2-05-BCF-S-0031",
    operation: "アーカイブ",
    result: "success",
    reason: "指摘解消済みにつきアーカイブ",
  },
  {
    id: "e18",
    occurred_at: "2026-06-05T11:00:00",
    event_type: "approval.act",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "承認",
    target_id: "SKD-ARC-ZZ-ZZ-IFC-A-0003",
    operation: "最終承認 (竣工)",
    result: "success",
    reason: null,
  },
  {
    id: "e19",
    occurred_at: "2026-06-04T14:45:00",
    event_type: "container.update",
    actor_id: "u5",
    actor_ip: "10.4.21.55",
    target_type: "コンテナ",
    target_id: "OKN-MEP-ZN2-ZZ-DR-M-0033",
    operation: "コンテナ改訂",
    result: "success",
    reason: null,
  },
  {
    id: "e20",
    occurred_at: "2026-06-03T08:00:00",
    event_type: "naming_rule.update",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "命名規則",
    target_id: "proj-ngy",
    operation: "命名規則更新",
    result: "success",
    reason: "土木区分 SEC3 追加",
  },
  // --- HKR: 北陸新幹線延伸工事 audit events ---
  {
    id: "e21",
    occurred_at: "2026-06-14T08:05:00",
    event_type: "project.create",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "プロジェクト",
    target_id: "proj-hkr",
    operation: "プロジェクト新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e22",
    occurred_at: "2026-06-13T10:15:00",
    event_type: "container.create",
    actor_id: "u4",
    actor_ip: "10.4.21.40",
    target_type: "コンテナ",
    target_id: "HKR-CVL-TN1-ZZ-DR-C-0001",
    operation: "コンテナ新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e23",
    occurred_at: "2026-06-13T13:45:00",
    event_type: "container.transition",
    actor_id: "u4",
    actor_ip: "10.4.21.40",
    target_type: "コンテナ",
    target_id: "HKR-CVL-TN1-ZZ-DR-C-0001",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e24",
    occurred_at: "2026-06-13T15:00:00",
    event_type: "approval.request",
    actor_id: "u4",
    actor_ip: "10.4.21.40",
    target_type: "承認",
    target_id: "HKR-STR-TN1-ZZ-M3-S-0003",
    operation: "承認申請",
    result: "success",
    reason: null,
  },
  {
    id: "e25",
    occurred_at: "2026-06-12T16:30:00",
    event_type: "container.naming.fail",
    actor_id: "u4",
    actor_ip: "10.4.21.40",
    target_type: "コンテナ",
    target_id: "hkr-str-brg-zz-bcf-s-007",
    operation: "命名規則検証",
    result: "warning",
    reason: "連番桁数不足 (4桁必須) · ボリューム区分 BRG 未登録",
  },
  {
    id: "e26",
    occurred_at: "2026-06-12T09:00:00",
    event_type: "user.login",
    actor_id: "u4",
    actor_ip: "10.4.21.40",
    target_type: "ユーザー",
    target_id: "u4",
    operation: "ログイン",
    result: "success",
    reason: null,
  },
  // --- SWG: 首都高速湾岸線 老朽化対策 audit events ---
  {
    id: "e27",
    occurred_at: "2026-06-11T08:00:00",
    event_type: "project.create",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "プロジェクト",
    target_id: "proj-swg",
    operation: "プロジェクト新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e28",
    occurred_at: "2026-06-11T10:30:00",
    event_type: "container.create",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "SWG-CVL-BRG-ZZ-DR-C-0001",
    operation: "コンテナ新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e29",
    occurred_at: "2026-06-11T14:00:00",
    event_type: "container.transition",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "SWG-CVL-BRG-ZZ-DR-C-0001",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e30",
    occurred_at: "2026-06-10T11:00:00",
    event_type: "approval.act",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "承認",
    target_id: "SWG-STR-BRG-ZZ-M3-S-0002",
    operation: "レビュー承認",
    result: "success",
    reason: null,
  },
  {
    id: "e31",
    occurred_at: "2026-06-10T09:20:00",
    event_type: "security.share",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "外部共有",
    target_id: "SWG-CVL-BRG-ZZ-DR-C-0001",
    operation: "外部共有申請",
    result: "denied",
    reason: "機密区分 limited — 外部共有は管理職承認が必要",
  },
  {
    id: "e32",
    occurred_at: "2026-06-09T08:45:00",
    event_type: "naming_rule.update",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "命名規則",
    target_id: "proj-swg",
    operation: "命名規則更新",
    result: "success",
    reason: "首都高 BRG ボリューム区分追加",
  },
  // --- KSH: 九州縦貫道路 audit events ---
  {
    id: "e33",
    occurred_at: "2026-06-08T08:00:00",
    event_type: "project.create",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "プロジェクト",
    target_id: "proj-ksh",
    operation: "プロジェクト新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e34",
    occurred_at: "2026-06-08T10:00:00",
    event_type: "container.create",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "KSH-CVL-ZZ-ZZ-DR-C-0011",
    operation: "コンテナ新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e35",
    occurred_at: "2026-06-08T14:00:00",
    event_type: "container.naming.fail",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "ksh-cvl-sec3-zz-dr-c-0",
    operation: "命名規則検証",
    result: "warning",
    reason: "小文字使用・連番桁数不足 (4桁必須)",
  },
  {
    id: "e36",
    occurred_at: "2026-06-07T16:00:00",
    event_type: "container.transition",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "KSH-CVL-ZZ-ZZ-DR-C-0011",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e37",
    occurred_at: "2026-06-07T10:00:00",
    event_type: "approval.request",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "承認",
    target_id: "KSH-ARC-ZZ-ZZ-IFC-A-0001",
    operation: "承認申請",
    result: "success",
    reason: null,
  },
  // --- HND: 羽田空港 T4 audit events ---
  {
    id: "e38",
    occurred_at: "2026-06-06T08:00:00",
    event_type: "project.create",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "プロジェクト",
    target_id: "proj-hnd",
    operation: "プロジェクト新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e39",
    occurred_at: "2026-06-06T10:30:00",
    event_type: "container.create",
    actor_id: "u3",
    actor_ip: "10.4.21.30",
    target_type: "コンテナ",
    target_id: "HND-ARC-T4-ZZ-DR-A-0001",
    operation: "コンテナ新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e40",
    occurred_at: "2026-06-06T14:00:00",
    event_type: "container.transition",
    actor_id: "u3",
    actor_ip: "10.4.21.30",
    target_type: "コンテナ",
    target_id: "HND-ARC-T4-ZZ-DR-A-0001",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e41",
    occurred_at: "2026-06-05T16:00:00",
    event_type: "security.classification",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "セキュリティ",
    target_id: "HND-ARC-T4-ZZ-DR-A-0001",
    operation: "機密区分変更",
    result: "success",
    reason: "空港保安上 confidential に格上げ",
  },
  {
    id: "e42",
    occurred_at: "2026-06-05T11:00:00",
    event_type: "approval.act",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "承認",
    target_id: "HND-ARC-T4-ZZ-IFC-A-0001",
    operation: "最終承認 (IFC 統合モデル)",
    result: "success",
    reason: null,
  },
  {
    id: "e43",
    occurred_at: "2026-06-04T13:00:00",
    event_type: "container.create",
    actor_id: "u5",
    actor_ip: "10.4.21.55",
    target_type: "コンテナ",
    target_id: "HND-MEP-T4-ZZ-DR-M-0009",
    operation: "コンテナ新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e44",
    occurred_at: "2026-06-04T09:00:00",
    event_type: "user.login",
    actor_id: "u3",
    actor_ip: "10.4.21.30",
    target_type: "ユーザー",
    target_id: "u3",
    operation: "ログイン",
    result: "success",
    reason: null,
  },
  // --- TWG: 東京湾岸防潮堤 audit events ---
  {
    id: "e45",
    occurred_at: "2026-06-14T07:30:00",
    event_type: "project.create",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "プロジェクト",
    target_id: "proj-twg",
    operation: "プロジェクト新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e46",
    occurred_at: "2026-06-14T09:00:00",
    event_type: "container.create",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "TWG-CVL-ZZ-ZZ-DR-C-0001",
    operation: "コンテナ新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e47",
    occurred_at: "2026-06-14T10:00:00",
    event_type: "container.transition",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "TWG-CVL-ZZ-ZZ-DR-C-0001",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e48",
    occurred_at: "2026-06-13T16:00:00",
    event_type: "container.naming.fail",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "twg-cvl-sec4-zz-dr-c-0",
    operation: "命名規則検証",
    result: "warning",
    reason: "小文字使用・連番桁数不足 (4桁必須)",
  },
  {
    id: "e49",
    occurred_at: "2026-06-13T14:00:00",
    event_type: "approval.request",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "承認",
    target_id: "TWG-CVL-ZZ-ZZ-DR-C-0001",
    operation: "承認申請",
    result: "success",
    reason: null,
  },
  {
    id: "e50",
    occurred_at: "2026-06-13T11:00:00",
    event_type: "security.classification",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "セキュリティ",
    target_id: "TWG-CVL-ZZ-ZZ-SP-C-0001",
    operation: "機密区分変更",
    result: "success",
    reason: "防災インフラ図書 confidential に格上げ",
  },
  {
    id: "e51",
    occurred_at: "2026-06-12T15:00:00",
    event_type: "container.update",
    actor_id: "u5",
    actor_ip: "10.4.21.55",
    target_type: "コンテナ",
    target_id: "TWG-MEP-ZZ-ZZ-DR-M-0004",
    operation: "コンテナ改訂",
    result: "success",
    reason: null,
  },
  {
    id: "e52",
    occurred_at: "2026-06-11T16:30:00",
    event_type: "approval.act",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "承認",
    target_id: "TWG-ARC-ZZ-ZZ-IFC-A-0001",
    operation: "IFC 統合モデル 最終承認",
    result: "success",
    reason: null,
  },
  {
    id: "e53",
    occurred_at: "2026-06-10T08:00:00",
    event_type: "naming_rule.update",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "命名規則",
    target_id: "proj-twg",
    operation: "命名規則更新",
    result: "success",
    reason: "防潮堤プロジェクト TWG 追加・ボリューム区分 SEC4 追加",
  },
  {
    id: "e54",
    occurred_at: "2026-06-09T14:00:00",
    event_type: "user.login",
    actor_id: "u5",
    actor_ip: "10.4.21.55",
    target_type: "ユーザー",
    target_id: "u5",
    operation: "ログイン",
    result: "success",
    reason: null,
  },
  {
    id: "e55",
    occurred_at: "2026-06-08T09:00:00",
    event_type: "container.archive",
    actor_id: "u9",
    actor_ip: "10.22.5.9",
    target_type: "コンテナ",
    target_id: "TWG-STR-ZZ-ZZ-BCF-S-0006",
    operation: "アーカイブ",
    result: "success",
    reason: "指摘解消済みにつきアーカイブ",
  },
];

/** Legacy display-shape fallback used by AuditLogsPage when API data is unavailable. */
export const auditSamples = auditLogs.map((log) => ({
  id: log.id,
  at: log.occurred_at,
  actorId: log.actor_id ?? null,
  actor: log.actor_id?.slice(0, 8) ?? "-",
  event: log.event_type,
  target: `${log.target_type}${log.target_id ? ` #${log.target_id.slice(0, 20)}` : ""}`,
  type: log.target_type,
  op: log.operation,
  result: log.result,
  ip: log.actor_ip ?? "-",
  reason: log.reason ?? "-",
}));

// ---------------------------------------------------------------------------
// Demo naming rule
// ---------------------------------------------------------------------------

export const demoNamingRule: NamingRuleResponse = {
  id: "nr-demo",
  project_id: "demo",
  separator: "-",
  is_default: false,
  segments: [
    {
      key: "Project",
      label: "プロジェクト",
      required: true,
      max_length: 5,
      min_length: 2,
      allowed_values: [
        "TKO",
        "OKN",
        "NGY",
        "OSK",
        "SKD",
        "HKR",
        "SWG",
        "KSH",
        "HND",
        "TWG",
      ],
      pattern: "^[A-Z]{2,5}$",
      description: "プロジェクトコード (大文字英字)",
    },
    {
      key: "Originator",
      label: "発信者",
      required: true,
      max_length: 4,
      min_length: 2,
      allowed_values: ["ARC", "STR", "MEP", "CVL", "ELC"],
      pattern: "^[A-Z]{2,4}$",
      description: "作成組織略称",
    },
    {
      key: "Volume",
      label: "区分/系統",
      required: true,
      max_length: 4,
      min_length: 2,
      allowed_values: [
        "XX",
        "ZZ",
        "ZN1",
        "ZN2",
        "ZN3",
        "SEC1",
        "SEC2",
        "SEC3",
        "BLK1",
        "BLK2",
        "BLK3",
        "TB1",
        "TB2",
        "PH1",
        "TN1",
        "TN2",
        "TN3",
        "BRG",
        "T4",
        "SEC4",
      ],
      pattern: null,
      description: "建物ボリューム・工区",
    },
    {
      key: "Level",
      label: "レベル",
      required: true,
      max_length: 3,
      min_length: 2,
      allowed_values: [
        "ZZ",
        "XX",
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "RF",
        "B1",
        "B2",
        "B3",
        "B4",
      ],
      pattern: null,
      description: "階数またはZZ(全体)/XX(複数階)",
    },
    {
      key: "Type",
      label: "種別",
      required: true,
      max_length: 3,
      min_length: 2,
      allowed_values: ["DR", "M3", "IFC", "BCF", "SP"],
      pattern: "^[A-Z0-9]{2,3}$",
      description: "情報種別コード",
    },
    {
      key: "Role",
      label: "ロール",
      required: true,
      max_length: 1,
      min_length: 1,
      allowed_values: ["A", "S", "M", "C", "E"],
      pattern: "^[A-Z]$",
      description: "作成者ロール (A=意匠, S=構造, M=設備, C=土木, E=電気)",
    },
    {
      key: "Number",
      label: "連番",
      required: true,
      max_length: 4,
      min_length: 4,
      allowed_values: [],
      pattern: "^[0-9]{4}$",
      description: "4桁ゼロ埋め連番",
    },
  ],
};

// ---------------------------------------------------------------------------
// State order
// ---------------------------------------------------------------------------

export const stateOrder: ContainerState[] = [
  "WIP",
  "Shared",
  "Published",
  "Archived",
];
