import type {
  AuditLog,
  ContainerState,
  ContainerType,
  InformationContainer,
  NamingRuleResponse,
  Project,
  SecurityLevel,
} from "@/types";

export interface DesignUser {
  id: string;
  name: string;
  initials: string;
  role: string;
  org: string;
  color: string;
}

export interface DemoContainer {
  id: string;
  projectId: string;
  identifier: string;
  title: string;
  type: ContainerType;
  state: ContainerState;
  revision: string;
  security: SecurityLevel;
  naming: "pass" | "warn" | "fail";
  owner: string;
  org: string;
  updated: string;
  size: string;
  ext: string;
  discipline: string;
  issue?: string;
}

// ---------------------------------------------------------------------------
// Users (10 total)
// ---------------------------------------------------------------------------

export const designUsers: DesignUser[] = [
  {
    id: "u1",
    name: "佐藤 健一",
    initials: "佐",
    role: "BIMマネージャー",
    org: "大成設計",
    color: "#2c63e6",
  },
  {
    id: "u2",
    name: "鈴木 由美",
    initials: "鈴",
    role: "情報管理者",
    org: "大成設計",
    color: "#14a85f",
  },
  {
    id: "u3",
    name: "高橋 誠",
    initials: "高",
    role: "意匠設計",
    org: "大成設計",
    color: "#d99a26",
  },
  {
    id: "u4",
    name: "田中 浩二",
    initials: "田",
    role: "構造設計",
    org: "東和構造",
    color: "#9b59b6",
  },
  {
    id: "u5",
    name: "伊藤 さくら",
    initials: "伊",
    role: "設備設計",
    org: "日本設備工業",
    color: "#e0483b",
  },
  {
    id: "u6",
    name: "山本 大輔",
    initials: "山",
    role: "承認者 / 主任",
    org: "発注者PMO",
    color: "#0d9488",
  },
  {
    id: "u7",
    name: "中村 隆",
    initials: "中",
    role: "土木技術者",
    org: "三和エンジニアリング",
    color: "#f97316",
  },
  {
    id: "u8",
    name: "小林 美咲",
    initials: "小",
    role: "施工管理",
    org: "関西総合設計",
    color: "#ec4899",
  },
  {
    id: "u9",
    name: "渡辺 剛",
    initials: "渡",
    role: "BIM担当",
    org: "東北建設設計",
    color: "#6366f1",
  },
  {
    id: "u10",
    name: "松本 幸子",
    initials: "松",
    role: "品質管理",
    org: "南洋建設設計",
    color: "#84cc16",
  },
];

export const userById = Object.fromEntries(designUsers.map((u) => [u.id, u]));

// ---------------------------------------------------------------------------
// Projects (5 total)
// ---------------------------------------------------------------------------

export const demoProject: Project = {
  id: "demo",
  organization_id: "org-tko",
  name: "東京中央ターミナル再開発",
  code: "TKO",
  description:
    "地上48階・地下4階の複合ターミナル。鉄道・商業・オフィス・ホテルを統合。",
  status: "active",
  start_date: "2025-04-01",
  end_date: "2028-03-31",
  applied_standard: "ISO 19650-2:2018",
};

const projectOkn: Project = {
  id: "proj-okn",
  organization_id: "org-okn",
  name: "沖縄国際観光リゾート整備",
  code: "OKN",
  description:
    "沖縄本島南部の大規模国際観光リゾート開発。ホテル・コンベンション・マリーナを含む複合施設。",
  status: "active",
  start_date: "2025-07-01",
  end_date: "2027-12-31",
  applied_standard: "ISO 19650-2:2018",
};

const projectNgy: Project = {
  id: "proj-ngy",
  organization_id: "org-ngy",
  name: "名古屋都市高速道路改修工事",
  code: "NGY",
  description:
    "名古屋都市高速道路の老朽化橋梁・トンネル区間の全面改修。交通影響最小化が最重要課題。",
  status: "active",
  start_date: "2025-01-15",
  end_date: "2028-09-30",
  applied_standard: "ISO 19650-2:2018",
};

const projectOsk: Project = {
  id: "proj-osk",
  organization_id: "org-osk",
  name: "大阪港湾複合施設整備",
  code: "OSK",
  description:
    "大阪港南港地区における物流・商業・公園の複合施設整備。地盤改良・護岸改修を含む。",
  status: "suspended",
  start_date: "2024-10-01",
  end_date: "2027-03-31",
  applied_standard: "ISO 19650-3:2020",
};

const projectSkd: Project = {
  id: "proj-skd",
  organization_id: "org-skd",
  name: "仙台駅東口再開発計画",
  code: "SKD",
  description:
    "仙台駅東口周辺の再開発事業。複合商業ビル・広場整備・歩行者デッキを整備。",
  status: "completed",
  start_date: "2023-04-01",
  end_date: "2026-03-31",
  applied_standard: "ISO 19650-2:2018",
};

export const demoProjects: Project[] = [
  demoProject,
  projectOkn,
  projectNgy,
  projectOsk,
  projectSkd,
];

// ---------------------------------------------------------------------------
// Containers — TKO (8 original)
// ---------------------------------------------------------------------------

export const demoContainers: DemoContainer[] = [
  {
    id: "c1",
    projectId: "demo",
    identifier: "TKO-ARC-XX-07-DR-A-0421",
    title: "基準階平面詳細図 (7F オフィス)",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u3",
    org: "大成設計",
    updated: "2026-05-28T11:24:00",
    size: "4.2 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c2",
    projectId: "demo",
    identifier: "TKO-STR-XX-ZZ-M3-S-0008",
    title: "全体構造解析モデル v8",
    type: "model",
    state: "Shared",
    revision: "P04.02",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-29T16:48:00",
    size: "218 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c3",
    projectId: "demo",
    identifier: "TKO-MEP-B2-B2-DR-M-0117",
    title: "地下2階 機械設備配管図",
    type: "drawing",
    state: "WIP",
    revision: "P02.05",
    security: "limited",
    naming: "warn",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-05-30T09:12:00",
    size: "7.8 MB",
    ext: "PDF",
    discipline: "設備",
    issue: "レベルコードがマスタ未登録 (B2)",
  },
  {
    id: "c4",
    projectId: "demo",
    identifier: "tko-arc-xx-12-dr-a-09",
    title: "12F 平面図 ドラフト",
    type: "drawing",
    state: "WIP",
    revision: "P01.01",
    security: "limited",
    naming: "fail",
    owner: "u3",
    org: "大成設計",
    updated: "2026-05-30T18:03:00",
    size: "3.1 MB",
    ext: "DWG",
    discipline: "意匠",
    issue: "小文字使用・連番桁数不足 (4桁必須)",
  },
  {
    id: "c5",
    projectId: "demo",
    identifier: "TKO-ARC-XX-ZZ-IFC-A-0003",
    title: "意匠統合 IFC モデル (連携用)",
    type: "ifc",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u1",
    org: "大成設計",
    updated: "2026-05-25T14:30:00",
    size: "512 MB",
    ext: "IFC",
    discipline: "意匠",
  },
  {
    id: "c6",
    projectId: "demo",
    identifier: "TKO-STR-XX-03-BCF-S-0044",
    title: "3F 梁貫通スリーブ干渉 指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.03",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-29T10:05:00",
    size: "82 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c7",
    projectId: "demo",
    identifier: "TKO-ARC-XX-XX-SP-A-0012",
    title: "内装仕上げ仕様書",
    type: "document",
    state: "Published",
    revision: "C03",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2026-05-20T13:18:00",
    size: "1.1 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c8",
    projectId: "demo",
    identifier: "TKO-MEP-XX-ZZ-M3-M-0021",
    title: "機械設備 統合モデル",
    type: "model",
    state: "WIP",
    revision: "P03.01",
    security: "confidential",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-05-30T15:42:00",
    size: "176 MB",
    ext: "RVT",
    discipline: "設備",
  },

  // OKN — 沖縄国際観光リゾート整備 (10 containers)
  {
    id: "c9",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZN1-ZZ-DR-A-0001",
    title: "ゾーン1 ホテル棟 配置計画図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u10",
    org: "南洋建設設計",
    updated: "2026-03-12T10:00:00",
    size: "5.4 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c10",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZN1-01-DR-A-0042",
    title: "ホテル棟 1F ロビー平面詳細図",
    type: "drawing",
    state: "Shared",
    revision: "P03.01",
    security: "limited",
    naming: "pass",
    owner: "u10",
    org: "南洋建設設計",
    updated: "2026-04-18T14:30:00",
    size: "6.2 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c11",
    projectId: "proj-okn",
    identifier: "OKN-STR-ZN1-ZZ-M3-S-0005",
    title: "ホテル棟 構造統合モデル",
    type: "model",
    state: "WIP",
    revision: "P02.03",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-10T09:15:00",
    size: "245 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c12",
    projectId: "proj-okn",
    identifier: "OKN-MEP-ZN2-ZZ-DR-M-0033",
    title: "コンベンション棟 空調設備図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-04-05T16:20:00",
    size: "8.9 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c13",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZN3-ZZ-IFC-A-0002",
    title: "マリーナ棟 IFC 統合モデル",
    type: "ifc",
    state: "Shared",
    revision: "P01.02",
    security: "limited",
    naming: "pass",
    owner: "u10",
    org: "南洋建設設計",
    updated: "2026-05-22T11:00:00",
    size: "380 MB",
    ext: "IFC",
    discipline: "意匠",
  },
  {
    id: "c14",
    projectId: "proj-okn",
    identifier: "OKN-STR-ZN1-03-BCF-S-0011",
    title: "3F 柱脚接合部 干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.01",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-25T13:45:00",
    size: "105 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c15",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZZ-ZZ-SP-A-0007",
    title: "外壁・屋根仕様書",
    type: "document",
    state: "Published",
    revision: "C01",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2026-03-30T10:00:00",
    size: "2.3 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c16",
    projectId: "proj-okn",
    identifier: "OKN-ELC-ZN2-ZZ-DR-E-0018",
    title: "コンベンション 電気幹線図",
    type: "drawing",
    state: "WIP",
    revision: "P01.04",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-05-29T17:00:00",
    size: "3.7 MB",
    ext: "PDF",
    discipline: "電気",
  },
  {
    id: "c17",
    projectId: "proj-okn",
    identifier: "OKN-ARC-ZN1-RF-DR-A-0088",
    title: "ホテル棟 屋上 詳細図",
    type: "drawing",
    state: "Archived",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u10",
    org: "南洋建設設計",
    updated: "2026-02-14T09:30:00",
    size: "4.0 MB",
    ext: "DWG",
    discipline: "意匠",
  },
  {
    id: "c18",
    projectId: "proj-okn",
    identifier: "okn-mep-zn3-zz-dr-m-04",
    title: "マリーナ 給排水 ドラフト",
    type: "drawing",
    state: "WIP",
    revision: "P01.00",
    security: "limited",
    naming: "fail",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-01T08:00:00",
    size: "2.8 MB",
    ext: "DWG",
    discipline: "設備",
    issue: "小文字使用・連番桁数不足 (4桁必須)",
  },

  // NGY — 名古屋都市高速道路改修工事 (10 containers)
  {
    id: "c19",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC1-ZZ-DR-C-0001",
    title: "第1工区 平面線形図",
    type: "drawing",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-04-20T10:00:00",
    size: "9.1 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c20",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC2-ZZ-DR-C-0022",
    title: "第2工区 橋梁一般図",
    type: "drawing",
    state: "Shared",
    revision: "P05.01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-15T14:00:00",
    size: "7.6 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c21",
    projectId: "proj-ngy",
    identifier: "NGY-STR-SEC1-ZZ-M3-S-0003",
    title: "第1工区 橋脚構造解析モデル",
    type: "model",
    state: "Published",
    revision: "C02",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-04-10T16:30:00",
    size: "192 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c22",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC3-ZZ-IFC-C-0001",
    title: "第3工区 トンネル IFC モデル",
    type: "ifc",
    state: "WIP",
    revision: "P02.02",
    security: "confidential",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-05-28T11:00:00",
    size: "620 MB",
    ext: "IFC",
    discipline: "土木",
  },
  {
    id: "c23",
    projectId: "proj-ngy",
    identifier: "NGY-STR-SEC2-04-BCF-S-0009",
    title: "4号橋梁 PC桁 干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.02",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-05-20T09:30:00",
    size: "78 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c24",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-ZZ-ZZ-SP-C-0005",
    title: "道路構造物 設計仕様書",
    type: "document",
    state: "Published",
    revision: "C02",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2026-03-15T13:00:00",
    size: "3.5 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c25",
    projectId: "proj-ngy",
    identifier: "NGY-MEP-SEC1-ZZ-DR-M-0044",
    title: "第1工区 トンネル換気設備図",
    type: "drawing",
    state: "Shared",
    revision: "P02.00",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-05-12T15:00:00",
    size: "6.3 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c26",
    projectId: "proj-ngy",
    identifier: "NGY-ELC-SEC2-ZZ-DR-E-0031",
    title: "第2工区 道路照明設計図",
    type: "drawing",
    state: "WIP",
    revision: "P01.03",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2026-06-02T10:00:00",
    size: "4.7 MB",
    ext: "DWG",
    discipline: "電気",
  },
  {
    id: "c27",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC1-ZZ-DR-C-0099",
    title: "第1工区 縦断面図 (旧版)",
    type: "drawing",
    state: "Archived",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-02-01T08:00:00",
    size: "5.5 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c28",
    projectId: "proj-ngy",
    identifier: "NGY-CVL-SEC3-B1-DR-C-07",
    title: "トンネル坑口 ドラフト",
    type: "drawing",
    state: "WIP",
    revision: "P01.00",
    security: "limited",
    naming: "warn",
    owner: "u7",
    org: "三和エンジニアリング",
    updated: "2026-06-05T09:00:00",
    size: "3.2 MB",
    ext: "DWG",
    discipline: "土木",
    issue: "連番桁数不足 (4桁必須)",
  },

  // OSK — 大阪港湾複合施設整備 (10 containers)
  {
    id: "c29",
    projectId: "proj-osk",
    identifier: "OSK-CVL-PH1-ZZ-DR-C-0001",
    title: "護岸改修 標準断面図",
    type: "drawing",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-08-10T10:00:00",
    size: "6.0 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c30",
    projectId: "proj-osk",
    identifier: "OSK-ARC-BLK1-01-DR-A-0015",
    title: "物流棟A 1F 平面図",
    type: "drawing",
    state: "Shared",
    revision: "P02.01",
    security: "limited",
    naming: "pass",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-10-22T14:00:00",
    size: "5.8 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c31",
    projectId: "proj-osk",
    identifier: "OSK-STR-BLK1-ZZ-M3-S-0004",
    title: "物流棟A 鉄骨構造モデル",
    type: "model",
    state: "WIP",
    revision: "P03.02",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2025-12-15T09:00:00",
    size: "155 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c32",
    projectId: "proj-osk",
    identifier: "OSK-CVL-PH1-ZZ-IFC-C-0001",
    title: "護岸・埋立 IFC モデル",
    type: "ifc",
    state: "Published",
    revision: "C01",
    security: "limited",
    naming: "pass",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-09-30T16:00:00",
    size: "290 MB",
    ext: "IFC",
    discipline: "土木",
  },
  {
    id: "c33",
    projectId: "proj-osk",
    identifier: "OSK-ARC-BLK2-ZZ-DR-A-0028",
    title: "商業棟B 外観パース図",
    type: "drawing",
    state: "Archived",
    revision: "C01",
    security: "public",
    naming: "pass",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-07-20T11:00:00",
    size: "8.4 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c34",
    projectId: "proj-osk",
    identifier: "OSK-MEP-BLK1-ZZ-DR-M-0019",
    title: "物流棟 消火設備平面図",
    type: "drawing",
    state: "Shared",
    revision: "P01.03",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2025-11-08T14:30:00",
    size: "7.1 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c35",
    projectId: "proj-osk",
    identifier: "OSK-STR-BLK2-04-BCF-S-0007",
    title: "4号柱 地盤沈下 干渉指摘",
    type: "bcf",
    state: "Shared",
    revision: "P01.01",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2025-12-20T10:00:00",
    size: "64 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c36",
    projectId: "proj-osk",
    identifier: "OSK-CVL-ZZ-ZZ-SP-C-0003",
    title: "地盤改良 設計仕様書",
    type: "document",
    state: "Published",
    revision: "C02",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2025-08-25T13:00:00",
    size: "4.2 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c37",
    projectId: "proj-osk",
    identifier: "OSK-ELC-BLK1-ZZ-DR-E-0024",
    title: "物流棟 受変電設備図",
    type: "drawing",
    state: "WIP",
    revision: "P02.00",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2025-12-28T16:00:00",
    size: "5.0 MB",
    ext: "DWG",
    discipline: "電気",
  },
  {
    id: "c38",
    projectId: "proj-osk",
    identifier: "osk-arc-blk3-zz-dr-a-0",
    title: "公園エリア 平面図 (暫定)",
    type: "drawing",
    state: "WIP",
    revision: "P01.00",
    security: "limited",
    naming: "fail",
    owner: "u8",
    org: "関西総合設計",
    updated: "2025-12-31T09:00:00",
    size: "2.0 MB",
    ext: "DWG",
    discipline: "意匠",
    issue: "小文字使用・連番桁数不足 (4桁必須)",
  },

  // SKD — 仙台駅東口再開発計画 (10 containers)
  {
    id: "c39",
    projectId: "proj-skd",
    identifier: "SKD-ARC-ZZ-ZZ-DR-A-0001",
    title: "全体配置計画図",
    type: "drawing",
    state: "Published",
    revision: "C04",
    security: "limited",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2025-12-01T10:00:00",
    size: "7.2 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c40",
    projectId: "proj-skd",
    identifier: "SKD-ARC-TB1-01-DR-A-0055",
    title: "商業棟1 1F 詳細平面図",
    type: "drawing",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2025-11-15T14:00:00",
    size: "6.5 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c41",
    projectId: "proj-skd",
    identifier: "SKD-STR-TB1-ZZ-M3-S-0007",
    title: "商業棟1 構造統合モデル (竣工版)",
    type: "model",
    state: "Archived",
    revision: "C05",
    security: "confidential",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2026-02-10T09:00:00",
    size: "310 MB",
    ext: "RVT",
    discipline: "構造",
  },
  {
    id: "c42",
    projectId: "proj-skd",
    identifier: "SKD-ARC-ZZ-ZZ-IFC-A-0003",
    title: "全体 IFC 竣工モデル",
    type: "ifc",
    state: "Published",
    revision: "C04",
    security: "limited",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2026-03-01T11:00:00",
    size: "725 MB",
    ext: "IFC",
    discipline: "意匠",
  },
  {
    id: "c43",
    projectId: "proj-skd",
    identifier: "SKD-MEP-TB2-ZZ-DR-M-0038",
    title: "商業棟2 機械設備竣工図",
    type: "drawing",
    state: "Published",
    revision: "C03",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2025-12-20T16:00:00",
    size: "9.3 MB",
    ext: "PDF",
    discipline: "設備",
  },
  {
    id: "c44",
    projectId: "proj-skd",
    identifier: "SKD-ELC-TB1-ZZ-DR-E-0022",
    title: "商業棟1 電気竣工図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u5",
    org: "日本設備工業",
    updated: "2025-12-18T14:00:00",
    size: "5.5 MB",
    ext: "PDF",
    discipline: "電気",
  },
  {
    id: "c45",
    projectId: "proj-skd",
    identifier: "SKD-CVL-ZZ-ZZ-DR-C-0009",
    title: "歩行者デッキ 構造図",
    type: "drawing",
    state: "Published",
    revision: "C02",
    security: "limited",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2025-11-30T10:00:00",
    size: "8.1 MB",
    ext: "PDF",
    discipline: "土木",
  },
  {
    id: "c46",
    projectId: "proj-skd",
    identifier: "SKD-ARC-ZZ-ZZ-SP-A-0018",
    title: "外構・景観仕様書 (竣工版)",
    type: "document",
    state: "Published",
    revision: "C03",
    security: "public",
    naming: "pass",
    owner: "u2",
    org: "大成設計",
    updated: "2025-12-10T13:00:00",
    size: "3.8 MB",
    ext: "PDF",
    discipline: "意匠",
  },
  {
    id: "c47",
    projectId: "proj-skd",
    identifier: "SKD-STR-TB2-05-BCF-S-0031",
    title: "5F スラブ開口 干渉指摘 (解決済)",
    type: "bcf",
    state: "Archived",
    revision: "P02.04",
    security: "limited",
    naming: "pass",
    owner: "u4",
    org: "東和構造",
    updated: "2025-09-15T09:00:00",
    size: "43 KB",
    ext: "BCF",
    discipline: "構造",
  },
  {
    id: "c48",
    projectId: "proj-skd",
    identifier: "SKD-ARC-ZZ-ZZ-SP-A-0020",
    title: "プロジェクト完了報告書",
    type: "document",
    state: "Published",
    revision: "C01",
    security: "public",
    naming: "pass",
    owner: "u9",
    org: "東北建設設計",
    updated: "2026-03-31T17:00:00",
    size: "12.7 MB",
    ext: "PDF",
    discipline: "意匠",
  },
];

/** Group containers by projectId for easy lookup */
export const containersByProject: Record<string, DemoContainer[]> = {};
for (const c of demoContainers) {
  if (!containersByProject[c.projectId]) containersByProject[c.projectId] = [];
  containersByProject[c.projectId].push(c);
}

// ---------------------------------------------------------------------------
// InformationContainers (mapped from demoContainers)
// ---------------------------------------------------------------------------

export const demoInformationContainers: InformationContainer[] =
  demoContainers.map((container) => ({
    id: container.id,
    project_id: container.projectId,
    identifier: container.identifier,
    title: container.title,
    container_type: container.type,
    current_state: container.state,
    current_revision: container.revision,
    current_branch: null,
    security_level: container.security,
    naming_valid: container.naming === "pass",
    naming_issues: container.issue ?? null,
    created_by: container.owner,
  }));

// ---------------------------------------------------------------------------
// Approvals (10 items)
// ---------------------------------------------------------------------------

export const approvals = [
  {
    id: "a1",
    containerId: "c2",
    identifier: "TKO-STR-XX-ZZ-M3-S-0008",
    title: "全体構造解析モデル v8",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u4",
    requestedAt: "2026-05-30T09:14:00Z",
    due: "2026-06-02",
    priority: "high",
    security: "confidential",
    projectId: "demo",
  },
  {
    id: "a2",
    containerId: "c6",
    identifier: "TKO-STR-XX-03-BCF-S-0044",
    title: "3F 梁貫通スリーブ干渉 指摘",
    stage: "check / review / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u4",
    requestedAt: "2026-05-28T14:22:00Z",
    due: "2026-05-31",
    priority: "high",
    security: "limited",
    projectId: "demo",
  },
  {
    id: "a3",
    containerId: "c1",
    identifier: "TKO-ARC-XX-07-DR-A-0421",
    title: "基準階平面詳細図 (7F オフィス)",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u3",
    requestedAt: "2026-05-29T11:05:00Z",
    due: "2026-06-01",
    priority: "medium",
    security: "limited",
    projectId: "demo",
  },
  {
    id: "a4",
    containerId: "c10",
    identifier: "OKN-ARC-ZN1-01-DR-A-0042",
    title: "ホテル棟 1F ロビー平面詳細図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u10",
    requestedAt: "2026-06-01T08:30:00Z",
    due: "2026-06-10",
    priority: "medium",
    security: "limited",
    projectId: "proj-okn",
  },
  {
    id: "a5",
    containerId: "c13",
    identifier: "OKN-ARC-ZN3-ZZ-IFC-A-0002",
    title: "マリーナ棟 IFC 統合モデル",
    stage: "check / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u10",
    requestedAt: "2026-06-02T16:45:00Z",
    due: "2026-06-15",
    priority: "high",
    security: "limited",
    projectId: "proj-okn",
  },
  {
    id: "a6",
    containerId: "c20",
    identifier: "NGY-CVL-SEC2-ZZ-DR-C-0022",
    title: "第2工区 橋梁一般図",
    stage: "review / authorise",
    from: "Shared",
    to: "Published",
    requestedBy: "u7",
    requestedAt: "2026-05-31T13:10:00Z",
    due: "2026-06-08",
    priority: "high",
    security: "limited",
    projectId: "proj-ngy",
  },
  {
    id: "a7",
    containerId: "c23",
    identifier: "NGY-STR-SEC2-04-BCF-S-0009",
    title: "4号橋梁 PC桁 干渉指摘",
    stage: "check / review / approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u4",
    requestedAt: "2026-05-30T10:20:00Z",
    due: "2026-06-05",
    priority: "medium",
    security: "limited",
    projectId: "proj-ngy",
  },
  {
    id: "a8",
    containerId: "c30",
    identifier: "OSK-ARC-BLK1-01-DR-A-0015",
    title: "物流棟A 1F 平面図",
    stage: "review / authorise",
    from: "WIP",
    to: "Shared",
    requestedBy: "u8",
    requestedAt: "2026-06-03T09:00:00Z",
    due: "2026-06-20",
    priority: "low",
    security: "limited",
    projectId: "proj-osk",
  },
  {
    id: "a9",
    containerId: "c34",
    identifier: "OSK-MEP-BLK1-ZZ-DR-M-0019",
    title: "物流棟 消火設備平面図",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u5",
    requestedAt: "2026-06-04T15:30:00Z",
    due: "2026-06-25",
    priority: "medium",
    security: "limited",
    projectId: "proj-osk",
  },
  {
    id: "a10",
    containerId: "c43",
    identifier: "SKD-MEP-TB2-ZZ-DR-M-0038",
    title: "商業棟2 機械設備竣工図",
    stage: "approve",
    from: "Shared",
    to: "Published",
    requestedBy: "u5",
    requestedAt: "2026-01-10T11:00:00Z",
    due: "2026-01-15",
    priority: "high",
    security: "limited",
    projectId: "proj-skd",
  },
] as const;

// ---------------------------------------------------------------------------
// Requirement documents (5 entries)
// ---------------------------------------------------------------------------

export const reqDocs = [
  {
    id: "d1",
    type: "EIR",
    title: "発注者情報要求事項 (EIR) — 東京中央ターミナル",
    revision: "C02",
    status: "approved",
    owner: "u6",
    items: 24,
    desc: "設計・施工各段階で要求する情報、フォーマット、提出時点を定義。",
  },
  {
    id: "d2",
    type: "BEP",
    title: "BIM実行計画書 (BEP) — 設計段階",
    revision: "P03.01",
    status: "review",
    owner: "u1",
    items: 38,
    desc: "情報生成の方針、責任分担、ソフト構成、座標系、品質保証を規定。",
  },
  {
    id: "d3",
    type: "MIDP",
    title: "マスター情報配信計画",
    revision: "P02.00",
    status: "review",
    owner: "u2",
    items: 52,
    desc: "全TIDPを統合した成果物提出スケジュール。",
  },
  {
    id: "d4",
    type: "EIR",
    title: "発注者情報要求事項 (EIR) — 沖縄国際観光リゾート整備",
    revision: "C01",
    status: "approved",
    owner: "u10",
    items: 18,
    desc: "沖縄リゾートプロジェクトにおけるBIM情報要件。環境・景観配慮要求を含む。",
  },
  {
    id: "d5",
    type: "BEP",
    title: "BIM実行計画書 (BEP) — 名古屋都市高速道路改修",
    revision: "P01.02",
    status: "review",
    owner: "u7",
    items: 29,
    desc: "道路・橋梁・トンネルに対応したBIM実行計画。点検・維持管理連携を含む。",
  },
] as const;

// ---------------------------------------------------------------------------
// Requirement items
// ---------------------------------------------------------------------------

export const requirementItems = [
  {
    no: "EIR-01",
    what: "各階平面図 (LOD300)",
    when: "Stage 4 完了時",
    how: "PDF + IFC2x3 / 命名規則準拠",
    who: "発注者・施工者",
    status: "met",
  },
  {
    no: "EIR-02",
    what: "統合構造解析モデル",
    when: "実施設計中間",
    how: "RVT + IFC4 / 座標系JGD2011",
    who: "構造監理",
    status: "met",
  },
  {
    no: "EIR-03",
    what: "設備統合モデル (機械/電気)",
    when: "実施設計完了",
    how: "RVT + COBie",
    who: "FM・施工者",
    status: "partial",
  },
  {
    no: "EIR-04",
    what: "竣工モデル (As-built)",
    when: "引渡時",
    how: "IFC4 + COBie / FM連携",
    who: "資産管理者",
    status: "open",
  },
] as const;

// ---------------------------------------------------------------------------
// Naming segments
// ---------------------------------------------------------------------------

export const namingSegments = [
  { key: "Project", label: "プロジェクト", ex: "TKO" },
  { key: "Originator", label: "発信者", ex: "ARC" },
  { key: "Volume", label: "区分/系統", ex: "XX" },
  { key: "Level", label: "レベル", ex: "07" },
  { key: "Type", label: "種別", ex: "DR" },
  { key: "Role", label: "ロール", ex: "A" },
  { key: "Number", label: "連番", ex: "0001" },
] as const;

// ---------------------------------------------------------------------------
// Audit logs — two representations
//
// `auditLogs` uses the AuditLog API type (for mockRouter / API responses).
// `auditSamples` uses the legacy display shape that AuditLogsPage expects as
//   its fallback (fields: at, actor, event, target, type, op, result, ip, reason).
// ---------------------------------------------------------------------------

export const auditLogs: AuditLog[] = [
  {
    id: "e1",
    occurred_at: "2026-06-14T09:22:18",
    event_type: "container.transition",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "コンテナ",
    target_id: "TKO-ARC-XX-07-DR-A-0421",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e2",
    occurred_at: "2026-06-13T16:48:40",
    event_type: "container.transition",
    actor_id: "u4",
    actor_ip: "10.4.21.40",
    target_type: "コンテナ",
    target_id: "TKO-STR-XX-ZZ-M3-S-0008",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e3",
    occurred_at: "2026-06-13T14:20:55",
    event_type: "approval.act",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "承認",
    target_id: "TKO-ARC-XX-01-DR-A-0205",
    operation: "レビュー承認",
    result: "success",
    reason: null,
  },
  {
    id: "e4",
    occurred_at: "2026-06-13T11:58:31",
    event_type: "security.share",
    actor_id: "u2",
    actor_ip: "10.4.21.51",
    target_type: "外部共有",
    target_id: "TKO-ARC-XX-ZZ-IFC-A-0003",
    operation: "外部共有申請",
    result: "denied",
    reason: "機密区分の承認者不足",
  },
  {
    id: "e5",
    occurred_at: "2026-06-12T18:03:12",
    event_type: "container.naming.fail",
    actor_id: "u3",
    actor_ip: "10.4.21.88",
    target_type: "コンテナ",
    target_id: "tko-arc-xx-12-dr-a-09",
    operation: "命名規則検証",
    result: "warning",
    reason: "連番桁数不足・小文字使用",
  },
  {
    id: "e6",
    occurred_at: "2026-06-12T10:30:00",
    event_type: "container.create",
    actor_id: "u10",
    actor_ip: "10.8.1.22",
    target_type: "コンテナ",
    target_id: "OKN-ARC-ZN1-01-DR-A-0042",
    operation: "コンテナ新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e7",
    occurred_at: "2026-06-11T14:15:44",
    event_type: "container.transition",
    actor_id: "u10",
    actor_ip: "10.8.1.22",
    target_type: "コンテナ",
    target_id: "OKN-ARC-ZN1-ZZ-DR-A-0001",
    operation: "Shared→Published",
    result: "success",
    reason: null,
  },
  {
    id: "e8",
    occurred_at: "2026-06-11T09:00:00",
    event_type: "user.login",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "ユーザー",
    target_id: "u7",
    operation: "ログイン",
    result: "success",
    reason: null,
  },
  {
    id: "e9",
    occurred_at: "2026-06-10T16:44:33",
    event_type: "container.naming.warn",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "コンテナ",
    target_id: "NGY-CVL-SEC3-B1-DR-C-07",
    operation: "命名規則検証",
    result: "warning",
    reason: "連番桁数不足 (4桁必須)",
  },
  {
    id: "e10",
    occurred_at: "2026-06-10T13:22:10",
    event_type: "approval.request",
    actor_id: "u7",
    actor_ip: "10.12.3.5",
    target_type: "承認",
    target_id: "NGY-CVL-SEC2-ZZ-DR-C-0022",
    operation: "承認申請",
    result: "success",
    reason: null,
  },
  {
    id: "e11",
    occurred_at: "2026-06-09T15:05:20",
    event_type: "container.update",
    actor_id: "u4",
    actor_ip: "10.4.21.40",
    target_type: "コンテナ",
    target_id: "NGY-STR-SEC1-ZZ-M3-S-0003",
    operation: "コンテナ改訂",
    result: "success",
    reason: null,
  },
  {
    id: "e12",
    occurred_at: "2026-06-09T11:30:00",
    event_type: "security.classification",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "セキュリティ",
    target_id: "OSK-STR-BLK1-ZZ-M3-S-0004",
    operation: "機密区分変更",
    result: "success",
    reason: "設計完了に伴い confidential → limited に緩和",
  },
  {
    id: "e13",
    occurred_at: "2026-06-08T17:48:00",
    event_type: "container.naming.fail",
    actor_id: "u8",
    actor_ip: "10.15.2.44",
    target_type: "コンテナ",
    target_id: "osk-arc-blk3-zz-dr-a-0",
    operation: "命名規則検証",
    result: "warning",
    reason: "小文字使用・連番桁数不足",
  },
  {
    id: "e14",
    occurred_at: "2026-06-08T10:12:05",
    event_type: "container.transition",
    actor_id: "u8",
    actor_ip: "10.15.2.44",
    target_type: "コンテナ",
    target_id: "OSK-CVL-PH1-ZZ-DR-C-0001",
    operation: "WIP→Shared 提出",
    result: "success",
    reason: null,
  },
  {
    id: "e15",
    occurred_at: "2026-06-07T14:00:00",
    event_type: "project.create",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "プロジェクト",
    target_id: "proj-okn",
    operation: "プロジェクト新規作成",
    result: "success",
    reason: null,
  },
  {
    id: "e16",
    occurred_at: "2026-06-06T09:30:00",
    event_type: "user.login",
    actor_id: "u9",
    actor_ip: "10.22.5.9",
    target_type: "ユーザー",
    target_id: "u9",
    operation: "ログイン",
    result: "success",
    reason: null,
  },
  {
    id: "e17",
    occurred_at: "2026-06-05T16:20:00",
    event_type: "container.archive",
    actor_id: "u9",
    actor_ip: "10.22.5.9",
    target_type: "コンテナ",
    target_id: "SKD-STR-TB2-05-BCF-S-0031",
    operation: "アーカイブ",
    result: "success",
    reason: "指摘解消済みにつきアーカイブ",
  },
  {
    id: "e18",
    occurred_at: "2026-06-05T11:00:00",
    event_type: "approval.act",
    actor_id: "u6",
    actor_ip: "10.4.20.7",
    target_type: "承認",
    target_id: "SKD-ARC-ZZ-ZZ-IFC-A-0003",
    operation: "最終承認 (竣工)",
    result: "success",
    reason: null,
  },
  {
    id: "e19",
    occurred_at: "2026-06-04T14:45:00",
    event_type: "container.update",
    actor_id: "u5",
    actor_ip: "10.4.21.55",
    target_type: "コンテナ",
    target_id: "OKN-MEP-ZN2-ZZ-DR-M-0033",
    operation: "コンテナ改訂",
    result: "success",
    reason: null,
  },
  {
    id: "e20",
    occurred_at: "2026-06-03T08:00:00",
    event_type: "naming_rule.update",
    actor_id: "u1",
    actor_ip: "10.4.21.10",
    target_type: "命名規則",
    target_id: "proj-ngy",
    operation: "命名規則更新",
    result: "success",
    reason: "土木区分 SEC3 追加",
  },
];

/** Legacy display-shape fallback used by AuditLogsPage when API data is unavailable. */
export const auditSamples = auditLogs.map((log) => ({
  id: log.id,
  at: log.occurred_at,
  actorId: log.actor_id ?? null,
  actor: log.actor_id?.slice(0, 8) ?? "-",
  event: log.event_type,
  target: `${log.target_type}${log.target_id ? ` #${log.target_id.slice(0, 20)}` : ""}`,
  type: log.target_type,
  op: log.operation,
  result: log.result,
  ip: log.actor_ip ?? "-",
  reason: log.reason ?? "-",
}));

// ---------------------------------------------------------------------------
// Demo naming rule
// ---------------------------------------------------------------------------

export const demoNamingRule: NamingRuleResponse = {
  id: "nr-demo",
  project_id: "demo",
  separator: "-",
  is_default: false,
  segments: [
    {
      key: "Project",
      label: "プロジェクト",
      required: true,
      max_length: 5,
      min_length: 2,
      allowed_values: ["TKO", "OKN", "NGY", "OSK", "SKD"],
      pattern: "^[A-Z]{2,5}$",
      description: "プロジェクトコード (大文字英字)",
    },
    {
      key: "Originator",
      label: "発信者",
      required: true,
      max_length: 4,
      min_length: 2,
      allowed_values: ["ARC", "STR", "MEP", "CVL", "ELC"],
      pattern: "^[A-Z]{2,4}$",
      description: "作成組織略称",
    },
    {
      key: "Volume",
      label: "区分/系統",
      required: true,
      max_length: 4,
      min_length: 2,
      allowed_values: [
        "XX",
        "ZZ",
        "ZN1",
        "ZN2",
        "ZN3",
        "SEC1",
        "SEC2",
        "SEC3",
        "BLK1",
        "BLK2",
        "BLK3",
        "TB1",
        "TB2",
        "PH1",
      ],
      pattern: null,
      description: "建物ボリューム・工区",
    },
    {
      key: "Level",
      label: "レベル",
      required: true,
      max_length: 3,
      min_length: 2,
      allowed_values: [
        "ZZ",
        "XX",
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "RF",
        "B1",
        "B2",
        "B3",
        "B4",
      ],
      pattern: null,
      description: "階数またはZZ(全体)/XX(複数階)",
    },
    {
      key: "Type",
      label: "種別",
      required: true,
      max_length: 3,
      min_length: 2,
      allowed_values: ["DR", "M3", "IFC", "BCF", "SP"],
      pattern: "^[A-Z0-9]{2,3}$",
      description: "情報種別コード",
    },
    {
      key: "Role",
      label: "ロール",
      required: true,
      max_length: 1,
      min_length: 1,
      allowed_values: ["A", "S", "M", "C", "E"],
      pattern: "^[A-Z]$",
      description: "作成者ロール (A=意匠, S=構造, M=設備, C=土木, E=電気)",
    },
    {
      key: "Number",
      label: "連番",
      required: true,
      max_length: 4,
      min_length: 4,
      allowed_values: [],
      pattern: "^[0-9]{4}$",
      description: "4桁ゼロ埋め連番",
    },
  ],
};

// ---------------------------------------------------------------------------
// State order
// ---------------------------------------------------------------------------

export const stateOrder: ContainerState[] = [
  "WIP",
  "Shared",
  "Published",
  "Archived",
];
